// Code generated by volt gen. DO NOT EDIT.
//
// Source: package itest/blog/app

// Package client calls the routes of package app over HTTP
// (spec §V4.10): one typed method per query route, one raw method per
// named controller route. It imports the data packages and the volt
// runtime only, never the server.
package client

import (
	"context"
	"net/http"

	"github.com/Piechutowski/volt"
	"github.com/Piechutowski/volt/itest/blog/db"
)

// Client calls package app at Base. The embedded volt.Client carries
// the http.Client and the wire format (JSON by default, or GOB).
type Client struct {
	volt.Client
}

// New returns a client for the server at base, e.g. "http://localhost:8888".
func New(base string) *Client {
	return &Client{volt.Client{Base: base}}
}

// Root calls GET / (Home.Index); the response is the caller's to read and close.
func (c *Client) Root(ctx context.Context) (*http.Response, error) {
	return c.Raw(ctx, "GET", volt.URL("/"))
}

// Teapot calls GET /teapot (Home.Teapot); the response is the caller's to read and close.
func (c *Client) Teapot(ctx context.Context) (*http.Response, error) {
	return c.Raw(ctx, "GET", volt.URL("/teapot"))
}

// Ping calls any /ping (Home.Ping); the response is the caller's to read and close.
func (c *Client) Ping(ctx context.Context) (*http.Response, error) {
	return c.Raw(ctx, "GET", volt.URL("/ping"))
}

// AdminStats calls GET /admin/stats (Admin.Stats); the response is the caller's to read and close.
func (c *Client) AdminStats(ctx context.Context) (*http.Response, error) {
	return c.Raw(ctx, "GET", volt.URL("/admin/stats"))
}

// OpsFail calls GET /ops/fail (Ops.Fail); the response is the caller's to read and close.
func (c *Client) OpsFail(ctx context.Context) (*http.Response, error) {
	return c.Raw(ctx, "GET", volt.URL("/ops/fail"))
}

// Users calls GET /users (Users.Index); the response is the caller's to read and close.
func (c *Client) Users(ctx context.Context) (*http.Response, error) {
	return c.Raw(ctx, "GET", volt.URL("/users"))
}

// NewUser calls GET /users/new (Users.New); the response is the caller's to read and close.
func (c *Client) NewUser(ctx context.Context) (*http.Response, error) {
	return c.Raw(ctx, "GET", volt.URL("/users/new"))
}

// User calls GET /users/:id(int32) (Users.Show); the response is the caller's to read and close.
func (c *Client) User(ctx context.Context, id int32) (*http.Response, error) {
	return c.Raw(ctx, "GET", volt.URL("/users/"+volt.SegInt(int64(id))))
}

// EditUser calls GET /users/:id(int32)/edit (Users.Edit); the response is the caller's to read and close.
func (c *Client) EditUser(ctx context.Context, id int32) (*http.Response, error) {
	return c.Raw(ctx, "GET", volt.URL("/users/"+volt.SegInt(int64(id))+"/edit"))
}

// Avatar calls GET /users/:id(int32)/avatar (Users.Avatar); the response is the caller's to read and close.
func (c *Client) Avatar(ctx context.Context, id int32) (*http.Response, error) {
	return c.Raw(ctx, "GET", volt.URL("/users/"+volt.SegInt(int64(id))+"/avatar"))
}

// Serve calls GET /files/:path... (Files.Serve); the response is the caller's to read and close.
func (c *Client) Serve(ctx context.Context, path string) (*http.Response, error) {
	return c.Raw(ctx, "GET", volt.URL("/files/"+volt.SegWild(path)))
}

// Tag calls GET /tags/:name (Tags.Show); the response is the caller's to read and close.
func (c *Client) Tag(ctx context.Context, name string) (*http.Response, error) {
	return c.Raw(ctx, "GET", volt.URL("/tags/"+volt.Seg(name)))
}

// Page calls GET /pages/:num(int) (Pages.Show); the response is the caller's to read and close.
func (c *Client) Page(ctx context.Context, num int) (*http.Response, error) {
	return c.Raw(ctx, "GET", volt.URL("/pages/"+volt.SegInt(int64(num))))
}

// Archive calls GET /archive/:stamp(int64) (Archive.Show); the response is the caller's to read and close.
func (c *Client) Archive(ctx context.Context, stamp int64) (*http.Response, error) {
	return c.Raw(ctx, "GET", volt.URL("/archive/"+volt.SegInt(stamp)))
}

// APIUserList calls GET /api/users (db.UserList).
func (c *Client) APIUserList(ctx context.Context) ([]db.User, error) {
	var out []db.User
	err := c.Do(ctx, "GET", volt.URL("/api/users"), nil, &out)
	return out, err
}

// APIUserGet calls GET /api/users/:id(int32) (db.UserGet).
func (c *Client) APIUserGet(ctx context.Context, id int32) (db.User, error) {
	var out db.User
	err := c.Do(ctx, "GET", volt.URL("/api/users/"+volt.SegInt(int64(id))), nil, &out)
	return out, err
}

// APIUserCreate calls POST /api/users (db.UserCreate).
func (c *Client) APIUserCreate(ctx context.Context, arg db.UserCreateParams) (db.User, error) {
	var out db.User
	err := c.Do(ctx, "POST", volt.URL("/api/users"), arg, &out)
	return out, err
}

// APIUserUpdate calls PATCH /api/users/:id(int32) (db.UserUpdate).
func (c *Client) APIUserUpdate(ctx context.Context, id int32, arg db.UserUpdateParams) (db.User, error) {
	var out db.User
	err := c.Do(ctx, "PATCH", volt.URL("/api/users/"+volt.SegInt(int64(id))), arg, &out)
	return out, err
}

// APIUserDelete calls DELETE /api/users/:id(int32) (db.UserDelete).
func (c *Client) APIUserDelete(ctx context.Context, id int32) error {
	return c.Do(ctx, "DELETE", volt.URL("/api/users/"+volt.SegInt(int64(id))), nil, nil)
}

// APIUserPicked calls GET /api/picked (db.UserPicked).
func (c *Client) APIUserPicked(ctx context.Context, ids []int32) ([]db.User, error) {
	q := []volt.URLOption{}
	for _, v := range ids {
		q = append(q, volt.Query("ids", volt.FormatQuery(v)))
	}
	var out []db.User
	err := c.Do(ctx, "GET", volt.URL("/api/picked", q...), nil, &out)
	return out, err
}
