// Code generated by nao gen from package .; DO NOT EDIT.
//
// Validators for the schema's checks (docs/spec.md §V12): typed
// checks evaluate exactly like their SQL CHECK twins; Go-reference
// checks call hand-written functions of this package.

package itest

import (
	"errors"
	"github.com/Piechutowski/volt/nao/rt"
)

// Validate evaluates every check of users against the row's values
// (spec §V12). Typed checks are also CHECK constraints in the DDL;
// Go-reference checks run here only — SQLite cannot call Go.
func (v User) Validate() error {
	var errs []error
	if err := EmailValid(v.Email); err != nil {
		errs = append(errs, rt.CheckError{Model: "User", Check: "EmailValid(email)", Cause: err})
	}
	return errors.Join(errs...)
}

// Validate evaluates every check of page_views against the row's values
// (spec §V12). Typed checks are also CHECK constraints in the DDL;
// Go-reference checks run here only — SQLite cannot call Go.
func (v PageView) Validate() error {
	var errs []error
	if !(v.Hits >= 0 && v.Day >= 1) {
		errs = append(errs, rt.CheckError{Model: "PageView", Check: "counts_positive"})
	}
	if !(rt.Like(v.Site, "%_")) {
		errs = append(errs, rt.CheckError{Model: "PageView", Check: "site LIKE '%_'"})
	}
	return errors.Join(errs...)
}
