// Code generated by nao gen from package nao/itest; DO NOT EDIT.
//
// Validators for the schema's checks (docs/spec.md §V12): typed
// checks evaluate exactly like their SQL CHECK twins; Go-reference
// checks call hand-written functions of this package.

package itest

import (
	"github.com/Piechutowski/volt/nao/rt"
)

// Validate evaluates every check of users against the row's values
// (spec §V12). Typed checks are also CHECK constraints in the DDL;
// Go-reference checks run here only — SQLite cannot call Go.
func (v User) Validate() error {
	var errs []rt.CheckError
	if err := EmailValid(v.Email); err != nil {
		errs = append(errs, rt.CheckError{Model: "User", Check: "EmailValid(email)", Columns: []string{"email"}, Cause: err})
	}
	return rt.Validation(errs)
}

// Validate evaluates the checks of users whose columns UserCreateParams carries
// (spec §V12.6).
func (v UserCreateParams) Validate() error {
	var errs []rt.CheckError
	if err := EmailValid(v.Email); err != nil {
		errs = append(errs, rt.CheckError{Model: "User", Check: "EmailValid(email)", Columns: []string{"email"}, Cause: err})
	}
	return rt.Validation(errs)
}

// Validate evaluates the checks of users whose columns UserUpdateParams carries
// (spec §V12.6).
func (v UserUpdateParams) Validate() error {
	var errs []rt.CheckError
	if err := EmailValid(v.Email); err != nil {
		errs = append(errs, rt.CheckError{Model: "User", Check: "EmailValid(email)", Columns: []string{"email"}, Cause: err})
	}
	return rt.Validation(errs)
}

// Validate evaluates every check of orders against the row's values
// (spec §V12). Typed checks are also CHECK constraints in the DDL;
// Go-reference checks run here only — SQLite cannot call Go.
func (v Order) Validate() error {
	var errs []rt.CheckError
	if !(v.Total != "") {
		errs = append(errs, rt.CheckError{Model: "Order", Check: "total_required", Columns: []string{"total"}})
	}
	return rt.Validation(errs)
}

// Validate evaluates the checks of orders whose columns OrderCreateParams carries
// (spec §V12.6).
func (v OrderCreateParams) Validate() error {
	var errs []rt.CheckError
	if !(v.Total != "") {
		errs = append(errs, rt.CheckError{Model: "Order", Check: "total_required", Columns: []string{"total"}})
	}
	return rt.Validation(errs)
}

// Validate evaluates the checks of orders whose columns OrderUpdateParams carries
// (spec §V12.6).
func (v OrderUpdateParams) Validate() error {
	var errs []rt.CheckError
	if !(v.Total != "") {
		errs = append(errs, rt.CheckError{Model: "Order", Check: "total_required", Columns: []string{"total"}})
	}
	return rt.Validation(errs)
}

// Validate evaluates every check of page_views against the row's values
// (spec §V12). Typed checks are also CHECK constraints in the DDL;
// Go-reference checks run here only — SQLite cannot call Go.
func (v PageView) Validate() error {
	var errs []rt.CheckError
	if !(v.Hits >= 0 && v.Day >= 1) {
		errs = append(errs, rt.CheckError{Model: "PageView", Check: "counts_positive", Columns: []string{"hits", "day"}})
	}
	if !(rt.Like(v.Site, "%_")) {
		errs = append(errs, rt.CheckError{Model: "PageView", Check: "site LIKE '%_'", Columns: []string{"site"}})
	}
	return rt.Validation(errs)
}

// Validate evaluates the checks of page_views whose columns PageViewCreateParams carries
// (spec §V12.6); left to the row and the DDL: counts_positive.
func (v PageViewCreateParams) Validate() error {
	var errs []rt.CheckError
	if !(rt.Like(v.Site, "%_")) {
		errs = append(errs, rt.CheckError{Model: "PageView", Check: "site LIKE '%_'", Columns: []string{"site"}})
	}
	return rt.Validation(errs)
}

// Validate evaluates the checks of page_views whose columns PageViewUpdateParams carries
// (spec §V12.6).
func (v PageViewUpdateParams) Validate() error {
	var errs []rt.CheckError
	if !(v.Hits >= 0 && v.Day >= 1) {
		errs = append(errs, rt.CheckError{Model: "PageView", Check: "counts_positive", Columns: []string{"hits", "day"}})
	}
	if !(rt.Like(v.Site, "%_")) {
		errs = append(errs, rt.CheckError{Model: "PageView", Check: "site LIKE '%_'", Columns: []string{"site"}})
	}
	return rt.Validation(errs)
}
