// Code generated by nao gen from package nao/itest; DO NOT EDIT.

// Package itest contains data models generated from package nao/itest.
//
// Integration-test fixture for the generated query surface.
package itest

import (
	"github.com/Piechutowski/volt/nao/rt"
	"time"
)

// EOrderStatus is the order_status enum.
type EOrderStatus string

const (
	EOrderStatusPending EOrderStatus = "pending"
	EOrderStatusShipped EOrderStatus = "shipped"
	// Terminal state
	EOrderStatusDelivered EOrderStatus = "delivered"
)

// User is a row of the users table.
type User struct {
	ID    int32  `db:"id" json:"id"`
	Email string `db:"email" json:"email"`
	Name  string `db:"name" json:"displayName"`
	// NULL until the user writes one
	Bio       rt.Null[string] `db:"bio" json:"bio"`
	CreatedAt time.Time       `db:"created_at" json:"created_at"`
}

// Order is a row of the orders table.
type Order struct {
	ID       int32              `db:"id" json:"id"`
	UserID   int32              `db:"user_id" json:"user_id"`
	Status   EOrderStatus       `db:"status" json:"status"`
	Total    string             `db:"total" json:"total"`
	PlacedAt rt.Null[time.Time] `db:"placed_at" json:"placed_at"`
}

// UserTag is a row of the user_tags table.
type UserTag struct {
	UserID int32  `db:"user_id" json:"user_id"`
	Tag    string `db:"tag" json:"tag"`
}

// PageView is a row of the page_views table.
type PageView struct {
	ID   int32  `db:"id" json:"id"`
	Site string `db:"site" json:"site"`
	Day  int32  `db:"day" json:"day"`
	Hits int32  `db:"hits" json:"hits"`
}

// LinkClick is a row of the link_clicks table.
type LinkClick struct {
	ID     int32  `db:"id" json:"id"`
	Site   string `db:"site" json:"site"`
	Day    int32  `db:"day" json:"day"`
	Target string `db:"target" json:"target"`
}
