// Code generated by nao gen from package .; DO NOT EDIT.
//
// Selects declared in the schema (docs/spec.md §V11): one method per
// group member, statically typed, prepare-validated.

package itest

import (
	"context"
	"database/sql"
)

const pageViewRowsSQL = `SELECT "id", "site", "day", "hits" FROM "page_views" WHERE (site = :site AND day = :day) ORDER BY day DESC, id ASC`

// PageViewRows runs the "Rows" select over page_views (spec §V11).
func (q *Queries) PageViewRows(ctx context.Context, site string, day int32) ([]PageView, error) {
	rows, err := q.db.QueryContext(ctx, pageViewRowsSQL, sql.Named("site", site), sql.Named("day", day))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []PageView
	for rows.Next() {
		v, err := pageViewScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

const linkClickRowsSQL = `SELECT "id", "site", "day", "target" FROM "link_clicks" WHERE (site = :site AND day = :day) ORDER BY day DESC, id ASC`

// LinkClickRows runs the "Rows" select over link_clicks (spec §V11).
func (q *Queries) LinkClickRows(ctx context.Context, site string, day int32) ([]LinkClick, error) {
	rows, err := q.db.QueryContext(ctx, linkClickRowsSQL, sql.Named("site", site), sql.Named("day", day))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []LinkClick
	for rows.Next() {
		v, err := linkClickScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

const pageViewRecentSQL = `SELECT "id", "site", "day", "hits" FROM "page_views" WHERE (site = :site AND day = :day) OR (day >= :from)`

// PageViewRecent runs the "Recent" select over page_views (spec §V11).
func (q *Queries) PageViewRecent(ctx context.Context, site string, day int32, from int32) ([]PageView, error) {
	rows, err := q.db.QueryContext(ctx, pageViewRecentSQL, sql.Named("site", site), sql.Named("day", day), sql.Named("from", from))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []PageView
	for rows.Next() {
		v, err := pageViewScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

const linkClickRecentSQL = `SELECT "id", "site", "day", "target" FROM "link_clicks" WHERE (site = :site AND day = :day) OR (day >= :from)`

// LinkClickRecent runs the "Recent" select over link_clicks (spec §V11).
func (q *Queries) LinkClickRecent(ctx context.Context, site string, day int32, from int32) ([]LinkClick, error) {
	rows, err := q.db.QueryContext(ctx, linkClickRecentSQL, sql.Named("site", site), sql.Named("day", day), sql.Named("from", from))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []LinkClick
	for rows.Next() {
		v, err := linkClickScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}
