// Code generated by nao gen from package .; DO NOT EDIT.
//
// CRUD methods over the models in nao_models.go. Identity arguments
// are positional, data arguments ride in params structs, and the SQL
// binds named placeholders — see docs/decisions.md D15-D17.

package itest

import (
	"context"
	"database/sql"
	"github.com/Piechutowski/volt/nao/rt"
	"strings"
	"time"
)

// Queries bundles the generated CRUD over one database handle: a
// *sql.DB, a *sql.Tx, or anything else satisfying rt.DBTX.
type Queries struct {
	db    rt.DBTX
	cache *rt.StmtCache
}

// New returns Queries running on db.
func New(db rt.DBTX) *Queries { return &Queries{db: db} }

// WithCache returns a copy of q whose dynamic queries (Query, Count,
// Exists, DeleteWhere, UpdateWhere) run through cache: identical option
// shapes render identical SQL, prepared once (D31). Bind a cache to a
// *sql.DB, never a transaction.
func (q *Queries) WithCache(cache *rt.StmtCache) *Queries {
	return &Queries{db: q.db, cache: cache}
}

// WithTx returns a copy of q running on tx. The statement cache does not
// follow: its statements are prepared on the outer handle (D31).
func (q *Queries) WithTx(tx *sql.Tx) *Queries { return &Queries{db: tx} }

// Tx runs fn inside a transaction: the Queries handed to fn joins it, a
// nil error commits, anything else rolls back. q must be backed by a
// handle that can begin a transaction (a *sql.DB).
func (q *Queries) Tx(ctx context.Context, fn func(*Queries) error) error {
	return rt.Tx(ctx, q.db, func(tx *sql.Tx) error { return fn(q.WithTx(tx)) })
}

// rowScanner is the shared surface of *sql.Row and *sql.Rows.
type rowScanner interface {
	Scan(dest ...any) error
}

// userScan reads one users row in generated column order.
func userScan(r rowScanner) (User, error) {
	var v User
	err := r.Scan(&v.ID, &v.Email, &v.Name, &v.Bio, &v.CreatedAt)
	return v, err
}

const userGetSQL = `SELECT "id", "email", "name", "bio", "created_at" FROM "users" WHERE "id" = :id`

// UserGet fetches the users row with the given primary key, or rt.ErrNotFound.
func (q *Queries) UserGet(ctx context.Context, id int32) (User, error) {
	return userScan(q.db.QueryRowContext(ctx, userGetSQL, sql.Named("id", id)))
}

const userGetManySQL = `SELECT "id", "email", "name", "bio", "created_at" FROM "users" WHERE "id" IN`

// UserGetMany fetches the users rows whose primary key is in ids, in
// database order. Missing keys are not an error; they are just absent.
func (q *Queries) UserGetMany(ctx context.Context, ids []int32) ([]User, error) {
	if len(ids) == 0 {
		return nil, nil
	}
	args := make([]any, len(ids))
	for i, k := range ids {
		args[i] = k
	}
	query := userGetManySQL + " (?" + strings.Repeat(", ?", len(ids)-1) + ")"
	rows, err := q.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []User
	for rows.Next() {
		v, err := userScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

const userGetByEmailSQL = `SELECT "id", "email", "name", "bio", "created_at" FROM "users" WHERE "email" = :email`

// UserGetByEmail fetches the users row with the given email (a unique column),
// or rt.ErrNotFound.
func (q *Queries) UserGetByEmail(ctx context.Context, email string) (User, error) {
	return userScan(q.db.QueryRowContext(ctx, userGetByEmailSQL, sql.Named("email", email)))
}

const userListSQL = `SELECT "id", "email", "name", "bio", "created_at" FROM "users"`

// UserList returns every users row.
func (q *Queries) UserList(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, userListSQL)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []User
	for rows.Next() {
		v, err := userScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

const userCreateSQL = `INSERT INTO "users" ("email", "name", "bio") VALUES (:email, :name, :bio) RETURNING "id", "email", "name", "bio", "created_at"`

// UserCreateParams are the caller-supplied columns of UserCreate. The
// auto-increment key and defaulted columns are the database's job (D16).
type UserCreateParams struct {
	Email string `db:"email" json:"email"`
	Name  string `db:"name" json:"name"`
	// NULL until the user writes one
	Bio rt.Null[string] `db:"bio" json:"bio"`
}

// UserCreate inserts a users row and returns the row the database wrote,
// generated keys and defaults filled in.
func (q *Queries) UserCreate(ctx context.Context, arg UserCreateParams) (User, error) {
	return userScan(q.db.QueryRowContext(ctx, userCreateSQL,
		sql.Named("email", arg.Email),
		sql.Named("name", arg.Name),
		sql.Named("bio", arg.Bio),
	))
}

const userUpdateSQL = `UPDATE "users" SET "email" = :email, "name" = :name, "bio" = :bio, "created_at" = :created_at WHERE "id" = :id RETURNING "id", "email", "name", "bio", "created_at"`

// UserUpdateParams are the data columns of UserUpdate: every column
// outside the primary key.
type UserUpdateParams struct {
	Email string `db:"email" json:"email"`
	Name  string `db:"name" json:"name"`
	// NULL until the user writes one
	Bio       rt.Null[string] `db:"bio" json:"bio"`
	CreatedAt time.Time       `db:"created_at" json:"created_at"`
}

// UserUpdate rewrites every non-key column of the identified users row
// and returns the result, or rt.ErrNotFound when no row matches.
func (q *Queries) UserUpdate(ctx context.Context, id int32, arg UserUpdateParams) (User, error) {
	return userScan(q.db.QueryRowContext(ctx, userUpdateSQL,
		sql.Named("id", id),
		sql.Named("email", arg.Email),
		sql.Named("name", arg.Name),
		sql.Named("bio", arg.Bio),
		sql.Named("created_at", arg.CreatedAt),
	))
}

const userDeleteSQL = `DELETE FROM "users" WHERE "id" = :id`

// UserDelete removes the identified users row; rt.ErrNotFound reports
// that nothing matched.
func (q *Queries) UserDelete(ctx context.Context, id int32) error {
	res, err := q.db.ExecContext(ctx, userDeleteSQL, sql.Named("id", id))
	if err != nil {
		return err
	}
	n, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if n == 0 {
		return rt.ErrNotFound
	}
	return nil
}

// orderScan reads one orders row in generated column order.
func orderScan(r rowScanner) (Order, error) {
	var v Order
	err := r.Scan(&v.ID, &v.UserID, &v.Status, &v.Total, &v.PlacedAt)
	return v, err
}

const orderGetSQL = `SELECT "id", "user_id", "status", "total", "placed_at" FROM "orders" WHERE "id" = :id`

// OrderGet fetches the orders row with the given primary key, or rt.ErrNotFound.
func (q *Queries) OrderGet(ctx context.Context, id int32) (Order, error) {
	return orderScan(q.db.QueryRowContext(ctx, orderGetSQL, sql.Named("id", id)))
}

const orderGetManySQL = `SELECT "id", "user_id", "status", "total", "placed_at" FROM "orders" WHERE "id" IN`

// OrderGetMany fetches the orders rows whose primary key is in ids, in
// database order. Missing keys are not an error; they are just absent.
func (q *Queries) OrderGetMany(ctx context.Context, ids []int32) ([]Order, error) {
	if len(ids) == 0 {
		return nil, nil
	}
	args := make([]any, len(ids))
	for i, k := range ids {
		args[i] = k
	}
	query := orderGetManySQL + " (?" + strings.Repeat(", ?", len(ids)-1) + ")"
	rows, err := q.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Order
	for rows.Next() {
		v, err := orderScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

const orderListSQL = `SELECT "id", "user_id", "status", "total", "placed_at" FROM "orders"`

// OrderList returns every orders row.
func (q *Queries) OrderList(ctx context.Context) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, orderListSQL)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Order
	for rows.Next() {
		v, err := orderScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

const orderCreateSQL = `INSERT INTO "orders" ("user_id", "total", "placed_at") VALUES (:user_id, :total, :placed_at) RETURNING "id", "user_id", "status", "total", "placed_at"`

// OrderCreateParams are the caller-supplied columns of OrderCreate. The
// auto-increment key and defaulted columns are the database's job (D16).
type OrderCreateParams struct {
	UserID   int32              `db:"user_id" json:"user_id"`
	Total    string             `db:"total" json:"total"`
	PlacedAt rt.Null[time.Time] `db:"placed_at" json:"placed_at"`
}

// OrderCreate inserts a orders row and returns the row the database wrote,
// generated keys and defaults filled in.
func (q *Queries) OrderCreate(ctx context.Context, arg OrderCreateParams) (Order, error) {
	return orderScan(q.db.QueryRowContext(ctx, orderCreateSQL,
		sql.Named("user_id", arg.UserID),
		sql.Named("total", arg.Total),
		sql.Named("placed_at", arg.PlacedAt),
	))
}

const orderUpdateSQL = `UPDATE "orders" SET "user_id" = :user_id, "status" = :status, "total" = :total, "placed_at" = :placed_at WHERE "id" = :id RETURNING "id", "user_id", "status", "total", "placed_at"`

// OrderUpdateParams are the data columns of OrderUpdate: every column
// outside the primary key.
type OrderUpdateParams struct {
	UserID   int32              `db:"user_id" json:"user_id"`
	Status   EOrderStatus       `db:"status" json:"status"`
	Total    string             `db:"total" json:"total"`
	PlacedAt rt.Null[time.Time] `db:"placed_at" json:"placed_at"`
}

// OrderUpdate rewrites every non-key column of the identified orders row
// and returns the result, or rt.ErrNotFound when no row matches.
func (q *Queries) OrderUpdate(ctx context.Context, id int32, arg OrderUpdateParams) (Order, error) {
	return orderScan(q.db.QueryRowContext(ctx, orderUpdateSQL,
		sql.Named("id", id),
		sql.Named("user_id", arg.UserID),
		sql.Named("status", arg.Status),
		sql.Named("total", arg.Total),
		sql.Named("placed_at", arg.PlacedAt),
	))
}

const orderDeleteSQL = `DELETE FROM "orders" WHERE "id" = :id`

// OrderDelete removes the identified orders row; rt.ErrNotFound reports
// that nothing matched.
func (q *Queries) OrderDelete(ctx context.Context, id int32) error {
	res, err := q.db.ExecContext(ctx, orderDeleteSQL, sql.Named("id", id))
	if err != nil {
		return err
	}
	n, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if n == 0 {
		return rt.ErrNotFound
	}
	return nil
}

// userTagScan reads one user_tags row in generated column order.
func userTagScan(r rowScanner) (UserTag, error) {
	var v UserTag
	err := r.Scan(&v.UserID, &v.Tag)
	return v, err
}

const userTagGetSQL = `SELECT "user_id", "tag" FROM "user_tags" WHERE "user_id" = :user_id AND "tag" = :tag`

// UserTagGet fetches the user_tags row with the given primary key, or rt.ErrNotFound.
func (q *Queries) UserTagGet(ctx context.Context, userID int32, tag string) (UserTag, error) {
	return userTagScan(q.db.QueryRowContext(ctx, userTagGetSQL, sql.Named("user_id", userID), sql.Named("tag", tag)))
}

const userTagListSQL = `SELECT "user_id", "tag" FROM "user_tags"`

// UserTagList returns every user_tags row.
func (q *Queries) UserTagList(ctx context.Context) ([]UserTag, error) {
	rows, err := q.db.QueryContext(ctx, userTagListSQL)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []UserTag
	for rows.Next() {
		v, err := userTagScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

const userTagCreateSQL = `INSERT INTO "user_tags" ("user_id", "tag") VALUES (:user_id, :tag) RETURNING "user_id", "tag"`

// UserTagCreateParams are the caller-supplied columns of UserTagCreate. The
// auto-increment key and defaulted columns are the database's job (D16).
type UserTagCreateParams struct {
	UserID int32  `db:"user_id" json:"user_id"`
	Tag    string `db:"tag" json:"tag"`
}

// UserTagCreate inserts a user_tags row and returns the row the database wrote,
// generated keys and defaults filled in.
func (q *Queries) UserTagCreate(ctx context.Context, arg UserTagCreateParams) (UserTag, error) {
	return userTagScan(q.db.QueryRowContext(ctx, userTagCreateSQL,
		sql.Named("user_id", arg.UserID),
		sql.Named("tag", arg.Tag),
	))
}

const userTagDeleteSQL = `DELETE FROM "user_tags" WHERE "user_id" = :user_id AND "tag" = :tag`

// UserTagDelete removes the identified user_tags row; rt.ErrNotFound reports
// that nothing matched.
func (q *Queries) UserTagDelete(ctx context.Context, userID int32, tag string) error {
	res, err := q.db.ExecContext(ctx, userTagDeleteSQL, sql.Named("user_id", userID), sql.Named("tag", tag))
	if err != nil {
		return err
	}
	n, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if n == 0 {
		return rt.ErrNotFound
	}
	return nil
}

// pageViewScan reads one page_views row in generated column order.
func pageViewScan(r rowScanner) (PageView, error) {
	var v PageView
	err := r.Scan(&v.ID, &v.Site, &v.Day, &v.Hits)
	return v, err
}

const pageViewGetSQL = `SELECT "id", "site", "day", "hits" FROM "page_views" WHERE "id" = :id`

// PageViewGet fetches the page_views row with the given primary key, or rt.ErrNotFound.
func (q *Queries) PageViewGet(ctx context.Context, id int32) (PageView, error) {
	return pageViewScan(q.db.QueryRowContext(ctx, pageViewGetSQL, sql.Named("id", id)))
}

const pageViewGetManySQL = `SELECT "id", "site", "day", "hits" FROM "page_views" WHERE "id" IN`

// PageViewGetMany fetches the page_views rows whose primary key is in ids, in
// database order. Missing keys are not an error; they are just absent.
func (q *Queries) PageViewGetMany(ctx context.Context, ids []int32) ([]PageView, error) {
	if len(ids) == 0 {
		return nil, nil
	}
	args := make([]any, len(ids))
	for i, k := range ids {
		args[i] = k
	}
	query := pageViewGetManySQL + " (?" + strings.Repeat(", ?", len(ids)-1) + ")"
	rows, err := q.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []PageView
	for rows.Next() {
		v, err := pageViewScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

const pageViewListSQL = `SELECT "id", "site", "day", "hits" FROM "page_views"`

// PageViewList returns every page_views row.
func (q *Queries) PageViewList(ctx context.Context) ([]PageView, error) {
	rows, err := q.db.QueryContext(ctx, pageViewListSQL)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []PageView
	for rows.Next() {
		v, err := pageViewScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

const pageViewCreateSQL = `INSERT INTO "page_views" ("site", "day") VALUES (:site, :day) RETURNING "id", "site", "day", "hits"`

// PageViewCreateParams are the caller-supplied columns of PageViewCreate. The
// auto-increment key and defaulted columns are the database's job (D16).
type PageViewCreateParams struct {
	Site string `db:"site" json:"site"`
	Day  int32  `db:"day" json:"day"`
}

// PageViewCreate inserts a page_views row and returns the row the database wrote,
// generated keys and defaults filled in.
func (q *Queries) PageViewCreate(ctx context.Context, arg PageViewCreateParams) (PageView, error) {
	return pageViewScan(q.db.QueryRowContext(ctx, pageViewCreateSQL,
		sql.Named("site", arg.Site),
		sql.Named("day", arg.Day),
	))
}

const pageViewUpdateSQL = `UPDATE "page_views" SET "site" = :site, "day" = :day, "hits" = :hits WHERE "id" = :id RETURNING "id", "site", "day", "hits"`

// PageViewUpdateParams are the data columns of PageViewUpdate: every column
// outside the primary key.
type PageViewUpdateParams struct {
	Site string `db:"site" json:"site"`
	Day  int32  `db:"day" json:"day"`
	Hits int32  `db:"hits" json:"hits"`
}

// PageViewUpdate rewrites every non-key column of the identified page_views row
// and returns the result, or rt.ErrNotFound when no row matches.
func (q *Queries) PageViewUpdate(ctx context.Context, id int32, arg PageViewUpdateParams) (PageView, error) {
	return pageViewScan(q.db.QueryRowContext(ctx, pageViewUpdateSQL,
		sql.Named("id", id),
		sql.Named("site", arg.Site),
		sql.Named("day", arg.Day),
		sql.Named("hits", arg.Hits),
	))
}

const pageViewDeleteSQL = `DELETE FROM "page_views" WHERE "id" = :id`

// PageViewDelete removes the identified page_views row; rt.ErrNotFound reports
// that nothing matched.
func (q *Queries) PageViewDelete(ctx context.Context, id int32) error {
	res, err := q.db.ExecContext(ctx, pageViewDeleteSQL, sql.Named("id", id))
	if err != nil {
		return err
	}
	n, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if n == 0 {
		return rt.ErrNotFound
	}
	return nil
}

// linkClickScan reads one link_clicks row in generated column order.
func linkClickScan(r rowScanner) (LinkClick, error) {
	var v LinkClick
	err := r.Scan(&v.ID, &v.Site, &v.Day, &v.Target)
	return v, err
}

const linkClickGetSQL = `SELECT "id", "site", "day", "target" FROM "link_clicks" WHERE "id" = :id`

// LinkClickGet fetches the link_clicks row with the given primary key, or rt.ErrNotFound.
func (q *Queries) LinkClickGet(ctx context.Context, id int32) (LinkClick, error) {
	return linkClickScan(q.db.QueryRowContext(ctx, linkClickGetSQL, sql.Named("id", id)))
}

const linkClickGetManySQL = `SELECT "id", "site", "day", "target" FROM "link_clicks" WHERE "id" IN`

// LinkClickGetMany fetches the link_clicks rows whose primary key is in ids, in
// database order. Missing keys are not an error; they are just absent.
func (q *Queries) LinkClickGetMany(ctx context.Context, ids []int32) ([]LinkClick, error) {
	if len(ids) == 0 {
		return nil, nil
	}
	args := make([]any, len(ids))
	for i, k := range ids {
		args[i] = k
	}
	query := linkClickGetManySQL + " (?" + strings.Repeat(", ?", len(ids)-1) + ")"
	rows, err := q.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []LinkClick
	for rows.Next() {
		v, err := linkClickScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

const linkClickListSQL = `SELECT "id", "site", "day", "target" FROM "link_clicks"`

// LinkClickList returns every link_clicks row.
func (q *Queries) LinkClickList(ctx context.Context) ([]LinkClick, error) {
	rows, err := q.db.QueryContext(ctx, linkClickListSQL)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []LinkClick
	for rows.Next() {
		v, err := linkClickScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

const linkClickCreateSQL = `INSERT INTO "link_clicks" ("site", "day") VALUES (:site, :day) RETURNING "id", "site", "day", "target"`

// LinkClickCreateParams are the caller-supplied columns of LinkClickCreate. The
// auto-increment key and defaulted columns are the database's job (D16).
type LinkClickCreateParams struct {
	Site string `db:"site" json:"site"`
	Day  int32  `db:"day" json:"day"`
}

// LinkClickCreate inserts a link_clicks row and returns the row the database wrote,
// generated keys and defaults filled in.
func (q *Queries) LinkClickCreate(ctx context.Context, arg LinkClickCreateParams) (LinkClick, error) {
	return linkClickScan(q.db.QueryRowContext(ctx, linkClickCreateSQL,
		sql.Named("site", arg.Site),
		sql.Named("day", arg.Day),
	))
}

const linkClickUpdateSQL = `UPDATE "link_clicks" SET "site" = :site, "day" = :day, "target" = :target WHERE "id" = :id RETURNING "id", "site", "day", "target"`

// LinkClickUpdateParams are the data columns of LinkClickUpdate: every column
// outside the primary key.
type LinkClickUpdateParams struct {
	Site   string `db:"site" json:"site"`
	Day    int32  `db:"day" json:"day"`
	Target string `db:"target" json:"target"`
}

// LinkClickUpdate rewrites every non-key column of the identified link_clicks row
// and returns the result, or rt.ErrNotFound when no row matches.
func (q *Queries) LinkClickUpdate(ctx context.Context, id int32, arg LinkClickUpdateParams) (LinkClick, error) {
	return linkClickScan(q.db.QueryRowContext(ctx, linkClickUpdateSQL,
		sql.Named("id", id),
		sql.Named("site", arg.Site),
		sql.Named("day", arg.Day),
		sql.Named("target", arg.Target),
	))
}

const linkClickDeleteSQL = `DELETE FROM "link_clicks" WHERE "id" = :id`

// LinkClickDelete removes the identified link_clicks row; rt.ErrNotFound reports
// that nothing matched.
func (q *Queries) LinkClickDelete(ctx context.Context, id int32) error {
	res, err := q.db.ExecContext(ctx, linkClickDeleteSQL, sql.Named("id", id))
	if err != nil {
		return err
	}
	n, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if n == 0 {
		return rt.ErrNotFound
	}
	return nil
}
