// Code generated by nao gen from package nao/itest; DO NOT EDIT.
//
// The dynamic query layer over the models in nao_models.go: typed
// column handles, per-model option wrappers, and predicate-driven
// terminals — see docs/decisions.md D28-D34.

package itest

import (
	"context"
	"github.com/Piechutowski/volt/nao/rt"
	"time"
)

// userTableSQL and userColumnsSQL are the fixed shape of User's
// dynamic statements; the interpreter renders everything else (D28).
const (
	userTableSQL   = `"users"`
	userColumnsSQL = `"id", "email", "name", "bio", "created_at"`
)

// Typed column handles of User (D29): inert predicate, order and
// assignment builders for the dynamic query layer (D28). A predicate
// built here can only enter User queries; mixing models is a compile
// error.
var (
	UserID        = rt.Column[User, int32]{Name: "id"}
	UserEmail     = rt.Column[User, string]{Name: "email"}
	UserName      = rt.Column[User, string]{Name: "name"}
	UserBio       = rt.NullColumn[User, string]{Column: rt.Column[User, string]{Name: "bio"}}
	UserCreatedAt = rt.Column[User, time.Time]{Name: "created_at"}
)

// UserLimit caps how many rows UserQuery returns (D30).
func UserLimit(n int) rt.Opt[User] { return rt.Limit[User](n) }

// UserOffset skips n rows; keyset pagination (UserAfter) scales better (D34).
func UserOffset(n int) rt.Opt[User] { return rt.Offset[User](n) }

// UserDistinct deduplicates the rows UserQuery returns.
func UserDistinct() rt.Opt[User] { return rt.Distinct[User]() }

// UserOrderBy sorts UserQuery's rows by Asc/Desc terms built on the
// User column handles.
func UserOrderBy(terms ...rt.Order[User]) rt.Opt[User] { return rt.OrderBy(terms...) }

// UserAfter resumes strictly after the row with the given key — keyset
// pagination (D34): one value per UserOrderBy term, in the same order.
func UserAfter(key ...any) rt.Opt[User] { return rt.After[User](key...) }

// UserSet collects the typed assignments of a UserUpdateWhere, built
// with Set/SetNull on the User column handles.
func UserSet(assigns ...rt.Assign[User]) []rt.Assign[User] { return assigns }

// UserQuery returns the users rows matching every given predicate,
// shaped by the remaining options (order, limit, offset, keyset,
// distinct). No options means every row.
func (q *Queries) UserQuery(ctx context.Context, opts ...rt.Opt[User]) ([]User, error) {
	query, args, err := rt.SelectRender(userTableSQL, userColumnsSQL, opts)
	if err != nil {
		return nil, err
	}
	rows, err := rt.StmtQuery(ctx, q.db, q.cache, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []User
	for rows.Next() {
		v, err := userScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

// UserCount reports how many users rows match every given predicate;
// none counts the whole table.
func (q *Queries) UserCount(ctx context.Context, preds ...rt.Pred[User]) (int64, error) {
	query, args, err := rt.CountRender(userTableSQL, preds)
	if err != nil {
		return 0, err
	}
	var n int64
	if err := rt.RowScan(ctx, q.db, q.cache, query, args, &n); err != nil {
		return 0, err
	}
	return n, nil
}

// UserExists reports whether any users row matches every given predicate.
func (q *Queries) UserExists(ctx context.Context, preds ...rt.Pred[User]) (bool, error) {
	query, args, err := rt.ExistsRender(userTableSQL, preds)
	if err != nil {
		return false, err
	}
	var found bool
	if err := rt.RowScan(ctx, q.db, q.cache, query, args, &found); err != nil {
		return false, err
	}
	return found, nil
}

// UserDeleteWhere removes every users row matching the predicates and
// reports how many went. No effective predicate is an error, never a
// full-table delete (D42).
func (q *Queries) UserDeleteWhere(ctx context.Context, preds ...rt.Pred[User]) (int64, error) {
	query, args, err := rt.DeleteRender(userTableSQL, preds)
	if err != nil {
		return 0, err
	}
	res, err := rt.StmtExec(ctx, q.db, q.cache, query, args...)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}

// UserUpdateWhere applies the typed assignments (UserSet) to every users
// row matching the predicates and reports how many changed — the
// partial update of the dynamic layer (D32). No effective predicate
// is an error, never a full-table rewrite (D42).
func (q *Queries) UserUpdateWhere(ctx context.Context, set []rt.Assign[User], preds ...rt.Pred[User]) (int64, error) {
	query, args, err := rt.UpdateRender(userTableSQL, set, preds)
	if err != nil {
		return 0, err
	}
	res, err := rt.StmtExec(ctx, q.db, q.cache, query, args...)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}

// orderTableSQL and orderColumnsSQL are the fixed shape of Order's
// dynamic statements; the interpreter renders everything else (D28).
const (
	orderTableSQL   = `"orders"`
	orderColumnsSQL = `"id", "user_id", "status", "total", "placed_at"`
)

// Typed column handles of Order (D29): inert predicate, order and
// assignment builders for the dynamic query layer (D28). A predicate
// built here can only enter Order queries; mixing models is a compile
// error.
var (
	OrderID       = rt.Column[Order, int32]{Name: "id"}
	OrderUserID   = rt.Column[Order, int32]{Name: "user_id"}
	OrderStatus   = rt.Column[Order, EOrderStatus]{Name: "status"}
	OrderTotal    = rt.Column[Order, string]{Name: "total"}
	OrderPlacedAt = rt.NullColumn[Order, time.Time]{Column: rt.Column[Order, time.Time]{Name: "placed_at"}}
)

// OrderLimit caps how many rows OrderQuery returns (D30).
func OrderLimit(n int) rt.Opt[Order] { return rt.Limit[Order](n) }

// OrderOffset skips n rows; keyset pagination (OrderAfter) scales better (D34).
func OrderOffset(n int) rt.Opt[Order] { return rt.Offset[Order](n) }

// OrderDistinct deduplicates the rows OrderQuery returns.
func OrderDistinct() rt.Opt[Order] { return rt.Distinct[Order]() }

// OrderOrderBy sorts OrderQuery's rows by Asc/Desc terms built on the
// Order column handles.
func OrderOrderBy(terms ...rt.Order[Order]) rt.Opt[Order] { return rt.OrderBy(terms...) }

// OrderAfter resumes strictly after the row with the given key — keyset
// pagination (D34): one value per OrderOrderBy term, in the same order.
func OrderAfter(key ...any) rt.Opt[Order] { return rt.After[Order](key...) }

// OrderSet collects the typed assignments of a OrderUpdateWhere, built
// with Set/SetNull on the Order column handles.
func OrderSet(assigns ...rt.Assign[Order]) []rt.Assign[Order] { return assigns }

// OrderQuery returns the orders rows matching every given predicate,
// shaped by the remaining options (order, limit, offset, keyset,
// distinct). No options means every row.
func (q *Queries) OrderQuery(ctx context.Context, opts ...rt.Opt[Order]) ([]Order, error) {
	query, args, err := rt.SelectRender(orderTableSQL, orderColumnsSQL, opts)
	if err != nil {
		return nil, err
	}
	rows, err := rt.StmtQuery(ctx, q.db, q.cache, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Order
	for rows.Next() {
		v, err := orderScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

// OrderCount reports how many orders rows match every given predicate;
// none counts the whole table.
func (q *Queries) OrderCount(ctx context.Context, preds ...rt.Pred[Order]) (int64, error) {
	query, args, err := rt.CountRender(orderTableSQL, preds)
	if err != nil {
		return 0, err
	}
	var n int64
	if err := rt.RowScan(ctx, q.db, q.cache, query, args, &n); err != nil {
		return 0, err
	}
	return n, nil
}

// OrderExists reports whether any orders row matches every given predicate.
func (q *Queries) OrderExists(ctx context.Context, preds ...rt.Pred[Order]) (bool, error) {
	query, args, err := rt.ExistsRender(orderTableSQL, preds)
	if err != nil {
		return false, err
	}
	var found bool
	if err := rt.RowScan(ctx, q.db, q.cache, query, args, &found); err != nil {
		return false, err
	}
	return found, nil
}

// OrderDeleteWhere removes every orders row matching the predicates and
// reports how many went. No effective predicate is an error, never a
// full-table delete (D42).
func (q *Queries) OrderDeleteWhere(ctx context.Context, preds ...rt.Pred[Order]) (int64, error) {
	query, args, err := rt.DeleteRender(orderTableSQL, preds)
	if err != nil {
		return 0, err
	}
	res, err := rt.StmtExec(ctx, q.db, q.cache, query, args...)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}

// OrderUpdateWhere applies the typed assignments (OrderSet) to every orders
// row matching the predicates and reports how many changed — the
// partial update of the dynamic layer (D32). No effective predicate
// is an error, never a full-table rewrite (D42).
func (q *Queries) OrderUpdateWhere(ctx context.Context, set []rt.Assign[Order], preds ...rt.Pred[Order]) (int64, error) {
	query, args, err := rt.UpdateRender(orderTableSQL, set, preds)
	if err != nil {
		return 0, err
	}
	res, err := rt.StmtExec(ctx, q.db, q.cache, query, args...)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}

// userTagTableSQL and userTagColumnsSQL are the fixed shape of UserTag's
// dynamic statements; the interpreter renders everything else (D28).
const (
	userTagTableSQL   = `"user_tags"`
	userTagColumnsSQL = `"user_id", "tag"`
)

// Typed column handles of UserTag (D29): inert predicate, order and
// assignment builders for the dynamic query layer (D28). A predicate
// built here can only enter UserTag queries; mixing models is a compile
// error.
var (
	UserTagUserID = rt.Column[UserTag, int32]{Name: "user_id"}
	UserTagTag    = rt.Column[UserTag, string]{Name: "tag"}
)

// UserTagLimit caps how many rows UserTagQuery returns (D30).
func UserTagLimit(n int) rt.Opt[UserTag] { return rt.Limit[UserTag](n) }

// UserTagOffset skips n rows; keyset pagination (UserTagAfter) scales better (D34).
func UserTagOffset(n int) rt.Opt[UserTag] { return rt.Offset[UserTag](n) }

// UserTagDistinct deduplicates the rows UserTagQuery returns.
func UserTagDistinct() rt.Opt[UserTag] { return rt.Distinct[UserTag]() }

// UserTagOrderBy sorts UserTagQuery's rows by Asc/Desc terms built on the
// UserTag column handles.
func UserTagOrderBy(terms ...rt.Order[UserTag]) rt.Opt[UserTag] { return rt.OrderBy(terms...) }

// UserTagAfter resumes strictly after the row with the given key — keyset
// pagination (D34): one value per UserTagOrderBy term, in the same order.
func UserTagAfter(key ...any) rt.Opt[UserTag] { return rt.After[UserTag](key...) }

// UserTagSet collects the typed assignments of a UserTagUpdateWhere, built
// with Set/SetNull on the UserTag column handles.
func UserTagSet(assigns ...rt.Assign[UserTag]) []rt.Assign[UserTag] { return assigns }

// UserTagQuery returns the user_tags rows matching every given predicate,
// shaped by the remaining options (order, limit, offset, keyset,
// distinct). No options means every row.
func (q *Queries) UserTagQuery(ctx context.Context, opts ...rt.Opt[UserTag]) ([]UserTag, error) {
	query, args, err := rt.SelectRender(userTagTableSQL, userTagColumnsSQL, opts)
	if err != nil {
		return nil, err
	}
	rows, err := rt.StmtQuery(ctx, q.db, q.cache, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []UserTag
	for rows.Next() {
		v, err := userTagScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

// UserTagCount reports how many user_tags rows match every given predicate;
// none counts the whole table.
func (q *Queries) UserTagCount(ctx context.Context, preds ...rt.Pred[UserTag]) (int64, error) {
	query, args, err := rt.CountRender(userTagTableSQL, preds)
	if err != nil {
		return 0, err
	}
	var n int64
	if err := rt.RowScan(ctx, q.db, q.cache, query, args, &n); err != nil {
		return 0, err
	}
	return n, nil
}

// UserTagExists reports whether any user_tags row matches every given predicate.
func (q *Queries) UserTagExists(ctx context.Context, preds ...rt.Pred[UserTag]) (bool, error) {
	query, args, err := rt.ExistsRender(userTagTableSQL, preds)
	if err != nil {
		return false, err
	}
	var found bool
	if err := rt.RowScan(ctx, q.db, q.cache, query, args, &found); err != nil {
		return false, err
	}
	return found, nil
}

// UserTagDeleteWhere removes every user_tags row matching the predicates and
// reports how many went. No effective predicate is an error, never a
// full-table delete (D42).
func (q *Queries) UserTagDeleteWhere(ctx context.Context, preds ...rt.Pred[UserTag]) (int64, error) {
	query, args, err := rt.DeleteRender(userTagTableSQL, preds)
	if err != nil {
		return 0, err
	}
	res, err := rt.StmtExec(ctx, q.db, q.cache, query, args...)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}

// UserTagUpdateWhere applies the typed assignments (UserTagSet) to every user_tags
// row matching the predicates and reports how many changed — the
// partial update of the dynamic layer (D32). No effective predicate
// is an error, never a full-table rewrite (D42).
func (q *Queries) UserTagUpdateWhere(ctx context.Context, set []rt.Assign[UserTag], preds ...rt.Pred[UserTag]) (int64, error) {
	query, args, err := rt.UpdateRender(userTagTableSQL, set, preds)
	if err != nil {
		return 0, err
	}
	res, err := rt.StmtExec(ctx, q.db, q.cache, query, args...)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}

// pageViewTableSQL and pageViewColumnsSQL are the fixed shape of PageView's
// dynamic statements; the interpreter renders everything else (D28).
const (
	pageViewTableSQL   = `"page_views"`
	pageViewColumnsSQL = `"id", "site", "day", "hits"`
)

// Typed column handles of PageView (D29): inert predicate, order and
// assignment builders for the dynamic query layer (D28). A predicate
// built here can only enter PageView queries; mixing models is a compile
// error.
var (
	PageViewID   = rt.Column[PageView, int32]{Name: "id"}
	PageViewSite = rt.Column[PageView, string]{Name: "site"}
	PageViewDay  = rt.Column[PageView, int32]{Name: "day"}
	PageViewHits = rt.Column[PageView, int32]{Name: "hits"}
)

// PageViewLimit caps how many rows PageViewQuery returns (D30).
func PageViewLimit(n int) rt.Opt[PageView] { return rt.Limit[PageView](n) }

// PageViewOffset skips n rows; keyset pagination (PageViewAfter) scales better (D34).
func PageViewOffset(n int) rt.Opt[PageView] { return rt.Offset[PageView](n) }

// PageViewDistinct deduplicates the rows PageViewQuery returns.
func PageViewDistinct() rt.Opt[PageView] { return rt.Distinct[PageView]() }

// PageViewOrderBy sorts PageViewQuery's rows by Asc/Desc terms built on the
// PageView column handles.
func PageViewOrderBy(terms ...rt.Order[PageView]) rt.Opt[PageView] { return rt.OrderBy(terms...) }

// PageViewAfter resumes strictly after the row with the given key — keyset
// pagination (D34): one value per PageViewOrderBy term, in the same order.
func PageViewAfter(key ...any) rt.Opt[PageView] { return rt.After[PageView](key...) }

// PageViewSet collects the typed assignments of a PageViewUpdateWhere, built
// with Set/SetNull on the PageView column handles.
func PageViewSet(assigns ...rt.Assign[PageView]) []rt.Assign[PageView] { return assigns }

// PageViewQuery returns the page_views rows matching every given predicate,
// shaped by the remaining options (order, limit, offset, keyset,
// distinct). No options means every row.
func (q *Queries) PageViewQuery(ctx context.Context, opts ...rt.Opt[PageView]) ([]PageView, error) {
	query, args, err := rt.SelectRender(pageViewTableSQL, pageViewColumnsSQL, opts)
	if err != nil {
		return nil, err
	}
	rows, err := rt.StmtQuery(ctx, q.db, q.cache, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []PageView
	for rows.Next() {
		v, err := pageViewScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

// PageViewCount reports how many page_views rows match every given predicate;
// none counts the whole table.
func (q *Queries) PageViewCount(ctx context.Context, preds ...rt.Pred[PageView]) (int64, error) {
	query, args, err := rt.CountRender(pageViewTableSQL, preds)
	if err != nil {
		return 0, err
	}
	var n int64
	if err := rt.RowScan(ctx, q.db, q.cache, query, args, &n); err != nil {
		return 0, err
	}
	return n, nil
}

// PageViewExists reports whether any page_views row matches every given predicate.
func (q *Queries) PageViewExists(ctx context.Context, preds ...rt.Pred[PageView]) (bool, error) {
	query, args, err := rt.ExistsRender(pageViewTableSQL, preds)
	if err != nil {
		return false, err
	}
	var found bool
	if err := rt.RowScan(ctx, q.db, q.cache, query, args, &found); err != nil {
		return false, err
	}
	return found, nil
}

// PageViewDeleteWhere removes every page_views row matching the predicates and
// reports how many went. No effective predicate is an error, never a
// full-table delete (D42).
func (q *Queries) PageViewDeleteWhere(ctx context.Context, preds ...rt.Pred[PageView]) (int64, error) {
	query, args, err := rt.DeleteRender(pageViewTableSQL, preds)
	if err != nil {
		return 0, err
	}
	res, err := rt.StmtExec(ctx, q.db, q.cache, query, args...)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}

// PageViewUpdateWhere applies the typed assignments (PageViewSet) to every page_views
// row matching the predicates and reports how many changed — the
// partial update of the dynamic layer (D32). No effective predicate
// is an error, never a full-table rewrite (D42).
func (q *Queries) PageViewUpdateWhere(ctx context.Context, set []rt.Assign[PageView], preds ...rt.Pred[PageView]) (int64, error) {
	query, args, err := rt.UpdateRender(pageViewTableSQL, set, preds)
	if err != nil {
		return 0, err
	}
	res, err := rt.StmtExec(ctx, q.db, q.cache, query, args...)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}

// linkClickTableSQL and linkClickColumnsSQL are the fixed shape of LinkClick's
// dynamic statements; the interpreter renders everything else (D28).
const (
	linkClickTableSQL   = `"link_clicks"`
	linkClickColumnsSQL = `"id", "site", "day", "target"`
)

// Typed column handles of LinkClick (D29): inert predicate, order and
// assignment builders for the dynamic query layer (D28). A predicate
// built here can only enter LinkClick queries; mixing models is a compile
// error.
var (
	LinkClickID     = rt.Column[LinkClick, int32]{Name: "id"}
	LinkClickSite   = rt.Column[LinkClick, string]{Name: "site"}
	LinkClickDay    = rt.Column[LinkClick, int32]{Name: "day"}
	LinkClickTarget = rt.Column[LinkClick, string]{Name: "target"}
)

// LinkClickLimit caps how many rows LinkClickQuery returns (D30).
func LinkClickLimit(n int) rt.Opt[LinkClick] { return rt.Limit[LinkClick](n) }

// LinkClickOffset skips n rows; keyset pagination (LinkClickAfter) scales better (D34).
func LinkClickOffset(n int) rt.Opt[LinkClick] { return rt.Offset[LinkClick](n) }

// LinkClickDistinct deduplicates the rows LinkClickQuery returns.
func LinkClickDistinct() rt.Opt[LinkClick] { return rt.Distinct[LinkClick]() }

// LinkClickOrderBy sorts LinkClickQuery's rows by Asc/Desc terms built on the
// LinkClick column handles.
func LinkClickOrderBy(terms ...rt.Order[LinkClick]) rt.Opt[LinkClick] { return rt.OrderBy(terms...) }

// LinkClickAfter resumes strictly after the row with the given key — keyset
// pagination (D34): one value per LinkClickOrderBy term, in the same order.
func LinkClickAfter(key ...any) rt.Opt[LinkClick] { return rt.After[LinkClick](key...) }

// LinkClickSet collects the typed assignments of a LinkClickUpdateWhere, built
// with Set/SetNull on the LinkClick column handles.
func LinkClickSet(assigns ...rt.Assign[LinkClick]) []rt.Assign[LinkClick] { return assigns }

// LinkClickQuery returns the link_clicks rows matching every given predicate,
// shaped by the remaining options (order, limit, offset, keyset,
// distinct). No options means every row.
func (q *Queries) LinkClickQuery(ctx context.Context, opts ...rt.Opt[LinkClick]) ([]LinkClick, error) {
	query, args, err := rt.SelectRender(linkClickTableSQL, linkClickColumnsSQL, opts)
	if err != nil {
		return nil, err
	}
	rows, err := rt.StmtQuery(ctx, q.db, q.cache, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []LinkClick
	for rows.Next() {
		v, err := linkClickScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

// LinkClickCount reports how many link_clicks rows match every given predicate;
// none counts the whole table.
func (q *Queries) LinkClickCount(ctx context.Context, preds ...rt.Pred[LinkClick]) (int64, error) {
	query, args, err := rt.CountRender(linkClickTableSQL, preds)
	if err != nil {
		return 0, err
	}
	var n int64
	if err := rt.RowScan(ctx, q.db, q.cache, query, args, &n); err != nil {
		return 0, err
	}
	return n, nil
}

// LinkClickExists reports whether any link_clicks row matches every given predicate.
func (q *Queries) LinkClickExists(ctx context.Context, preds ...rt.Pred[LinkClick]) (bool, error) {
	query, args, err := rt.ExistsRender(linkClickTableSQL, preds)
	if err != nil {
		return false, err
	}
	var found bool
	if err := rt.RowScan(ctx, q.db, q.cache, query, args, &found); err != nil {
		return false, err
	}
	return found, nil
}

// LinkClickDeleteWhere removes every link_clicks row matching the predicates and
// reports how many went. No effective predicate is an error, never a
// full-table delete (D42).
func (q *Queries) LinkClickDeleteWhere(ctx context.Context, preds ...rt.Pred[LinkClick]) (int64, error) {
	query, args, err := rt.DeleteRender(linkClickTableSQL, preds)
	if err != nil {
		return 0, err
	}
	res, err := rt.StmtExec(ctx, q.db, q.cache, query, args...)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}

// LinkClickUpdateWhere applies the typed assignments (LinkClickSet) to every link_clicks
// row matching the predicates and reports how many changed — the
// partial update of the dynamic layer (D32). No effective predicate
// is an error, never a full-table rewrite (D42).
func (q *Queries) LinkClickUpdateWhere(ctx context.Context, set []rt.Assign[LinkClick], preds ...rt.Pred[LinkClick]) (int64, error) {
	query, args, err := rt.UpdateRender(linkClickTableSQL, set, preds)
	if err != nil {
		return 0, err
	}
	res, err := rt.StmtExec(ctx, q.db, q.cache, query, args...)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}
