// Package volt is the runtime for code generated by the volt CLI: the
// handler shim with its error spine, the reverse-URL building blocks,
// the route-table types, and a minimal middleware set.
//
// The package is deliberately small and stdlib-only (nao's rt contract,
// D03, applied to the router): generated code imports the standard
// library and this package, nothing else. Middleware everywhere uses
// the ecosystem contract func(http.Handler) http.Handler (R8);
// controller methods carry the one non-stdlib shape in the system,
// func(http.ResponseWriter, *volt.Request, params...) error (R3).
package volt

import (
	"database/sql"
	"errors"
	"log/slog"
	"net/http"
)

// Request wraps *http.Request with route identity. It is passed to
// controller methods; everything else about the request is the embedded
// stdlib value.
type Request struct {
	*http.Request
	route string
	w     *statusWriter
}

// Route returns the matched route's ServeMux pattern (metrics-safe
// cardinality, ROUTE-19 parity).
func (r *Request) Route() string { return r.route }

// Committed reports whether the response header has been written. An
// error returned after commit reaches the error handler in log-only
// mode (§4.1 of the router spec).
func (r *Request) Committed() bool { return r.w != nil && r.w.wrote }

// HandlerFunc is the controller-side shape after parameter binding.
type HandlerFunc func(http.ResponseWriter, *Request) error

// ErrorHandler consumes a handler error. When Request.Committed() is
// true it must not write status or body.
type ErrorHandler func(http.ResponseWriter, *Request, error)

// Handler adapts a HandlerFunc plus an ErrorHandler into a std
// http.Handler; generated registrations wrap every route through it.
func Handler(route string, h HandlerFunc, eh ErrorHandler) http.Handler {
	if eh == nil {
		eh = DefaultErrorHandler
	}
	return http.HandlerFunc(func(w http.ResponseWriter, hr *http.Request) {
		sw := &statusWriter{ResponseWriter: w}
		req := &Request{Request: hr, route: route, w: sw}
		if err := h(sw, req); err != nil {
			eh(sw, req, err)
		}
	})
}

// DefaultErrorHandler maps HTTPError to its status and message, a
// query's row miss (sql.ErrNoRows, which nao's rt.ErrNotFound is) to
// 404, and everything else to a generic 500, logging the underlying
// error. On a committed response it only logs.
func DefaultErrorHandler(w http.ResponseWriter, r *Request, err error) {
	if r.Committed() {
		slog.Error("volt: handler error after response commit", "route", r.Route(), "err", err)
		return
	}
	var he HTTPError
	if errors.As(err, &he) {
		http.Error(w, he.Error(), he.StatusCode())
		return
	}
	if errors.Is(err, sql.ErrNoRows) {
		http.Error(w, "not found", http.StatusNotFound)
		return
	}
	slog.Error("volt: handler error", "route", r.Route(), "err", err)
	http.Error(w, "internal server error", http.StatusInternalServerError)
}

// Chain composes middleware around h: the first element is outermost,
// matching pipeline declaration order.
func Chain(h http.Handler, mw ...func(http.Handler) http.Handler) http.Handler {
	for i := len(mw) - 1; i >= 0; i-- {
		h = mw[i](h)
	}
	return h
}

// statusWriter records whether the header has been written, feeding
// Request.Committed and the Logger middleware.
type statusWriter struct {
	http.ResponseWriter
	status int
	wrote  bool
}

func (w *statusWriter) WriteHeader(code int) {
	if !w.wrote {
		w.wrote = true
		w.status = code
	}
	w.ResponseWriter.WriteHeader(code)
}

func (w *statusWriter) Write(b []byte) (int, error) {
	if !w.wrote {
		w.wrote = true
		w.status = http.StatusOK
	}
	return w.ResponseWriter.Write(b)
}

// Flush forwards http.Flusher so streaming handlers keep working
// through the shim. Flushing commits the response (the header goes out
// as 200 if not yet written), so it marks the writer committed first.
func (w *statusWriter) Flush() {
	if f, ok := w.ResponseWriter.(http.Flusher); ok {
		if !w.wrote {
			w.wrote = true
			w.status = http.StatusOK
		}
		f.Flush()
	}
}

// Unwrap exposes the underlying writer to http.ResponseController, so
// SetReadDeadline, Hijack and friends reach the real connection.
func (w *statusWriter) Unwrap() http.ResponseWriter { return w.ResponseWriter }

// Route is one row of the generated route table (volt_routes.go).
type Route struct {
	Method     string // "" for the any-verb
	Pattern    string // ServeMux pattern
	Spelled    string // DSL spelling
	Controller string
	Action     string
	Query      string // "pkg.Method" for a query route (§V4.8); Controller and Action are then empty
	Helper     string // reverse-URL function name, "" when none
	Params     []RouteParam
}

// RouteParam describes one captured parameter of a table row.
type RouteParam struct {
	Name string
	Type string // int, int32, int64, string
	Wild bool
}
