// Code generated by nao gen. DO NOT EDIT.
// (Illustrative excerpt — hand-written to show what the generator emits today.)
package db

// DaRR — Ilości referencyjne.
type DaRR struct {
	Idpk int64
	Idgr string
	Rok  int64
	// Czy w roku 2024 rolnik uczestniczył w systemie dla małych
	// gospodarstw? [T/N], j.m.=kod, słownik=TakNie
	RRPlatsmgTn string
	// Kwota płatności w ramach systemu dla małych gospodarstw, j.m.=zł
	RRPlatsmgZl float64
	// Czy przysługiwało prawo do płatności do powierzchni uprawy buraków
	// cukrowych? [T/N], j.m.=kod, słownik=TakNie
	RRPlatbcTn string
	// Powierzchnia uprawy buraków cukrowych objęta płatnością, j.m.=ha
	RRPlatbcHa float64
}

type DaRRCreateParams struct {
	Idgr        string
	Rok         int64
	RRPlatsmgTn string
	RRPlatsmgZl float64
	RRPlatbcTn  string
	RRPlatbcHa  float64
}

// DaIU — Uprawy.
type DaIU struct {
	Idpk  int64
	Idgr  string
	Rok   int64
	IUKod string  // Kod, j.m.=kod, słownik=Kody
	IUPow float64 // Powierzchnia, j.m.=ha
	IUZb  float64 // Zbiór, j.m.=dt
}

// Queries also carries (illustrative signatures):
//   DaRRLatestRok(ctx) (int64, error)                      — the Select block
//   DaRRGrid(ctx, volt.GridQuery) ([]DaRR, int, error)     — dataset list (nao v2 predicates)
//   DaRRCreate(ctx, DaRRCreateParams) (DaRR, error)
//   DaRRUpdate/DaRRDelete, and the DaIU* family symmetrically.
