// Code generated by nao gen. DO NOT EDIT.
// (Illustrative excerpt — hand-written to show what the generator emits today.)
package db

// MsRevenue — Revenue by region and year.
type MsRevenue struct {
	Id     int64
	Region string
	Year   int64
	// Is the plan billed on a recurring schedule? [Y/N], unit=code, dict=YesNo
	RevRecurringFlag string
	// Revenue from recurring plans, unit=EUR
	RevRecurringAmt float64
	// Was a volume discount applied? [Y/N], unit=code, dict=YesNo
	RevDiscountFlag string
	// Share of revenue discounted, unit=%
	RevDiscountPct float64
}

type MsRevenueCreateParams struct {
	Region           string
	Year             int64
	RevRecurringFlag string
	RevRecurringAmt  float64
	RevDiscountFlag  string
	RevDiscountPct   float64
}

// MsUsage — Feature usage.
type MsUsage struct {
	Id       int64
	Region   string
	Year     int64
	UseCode  string  // Feature code, unit=code, dict=Features
	UseSeats float64 // Licensed seats, unit=seats
	UseCalls float64 // API calls, unit=thousands
}

// Queries also carries (illustrative signatures):
//   MsRevenueLatestYear(ctx) (int64, error)                     — the Select block
//   MsRevenueGrid(ctx, volt.GridQuery) ([]MsRevenue, int, error) — dataset list (nao v2 predicates)
//   MsRevenueCreate(ctx, MsRevenueCreateParams) (MsRevenue, error)
//   MsRevenueUpdate/MsRevenueDelete, and the MsUsage* family symmetrically.
