// Code generated by nao gen from package itest/blog/db; DO NOT EDIT.
//
// Selects declared in the schema (docs/spec.md §V11): one method per
// group member, statically typed, prepare-validated.

package db

import (
	"context"
	"database/sql"
	"github.com/Piechutowski/volt/nao/rt"
)

const userPickedSQL = `SELECT "id", "email" FROM "users" WHERE id IN (SELECT value FROM json_each(:ids)) ORDER BY id ASC`

// UserPicked runs the "picked" select over users (spec §V11).
func (q *Queries) UserPicked(ctx context.Context, ids []int32) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, userPickedSQL, sql.Named("ids", rt.JSONList(ids)))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []User{}
	for rows.Next() {
		v, err := userScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}
