// Code generated by nao gen from package itest/blog/db; DO NOT EDIT.

// Package db contains data models generated from package itest/blog/db.
package db

// User is a row of the users table.
type User struct {
	ID    int32  `db:"id" json:"id"`
	Email string `db:"email" json:"email"`
}

// MsRevenue is a row of the ms_revenue table.
type MsRevenue struct {
	ID   int32  `db:"id" json:"id"`
	Org  string `db:"org" json:"org"`
	Year int32  `db:"year" json:"year"`
}

// MsUsage is a row of the ms_usage table.
type MsUsage struct {
	ID   int32  `db:"id" json:"id"`
	Org  string `db:"org" json:"org"`
	Year int32  `db:"year" json:"year"`
}
