// Code generated by nao gen from package itest/blog/db; DO NOT EDIT.
//
// CRUD methods over the models in nao_models.go. Identity arguments
// are positional, data arguments ride in params structs, and the SQL
// binds named placeholders — see docs/decisions.md D15-D17.

package db

import (
	"context"
	"database/sql"
	"github.com/Piechutowski/volt/nao/rt"
	"strings"
)

// Queries bundles the generated CRUD over one database handle: a
// *sql.DB, a *sql.Tx, or anything else satisfying rt.DBTX.
type Queries struct {
	db    rt.DBTX
	cache *rt.StmtCache
}

// New returns Queries running on db.
func New(db rt.DBTX) *Queries { return &Queries{db: db} }

// WithCache returns a copy of q whose dynamic queries (Query, Count,
// Exists, DeleteWhere, UpdateWhere) run through cache: identical option
// shapes render identical SQL, prepared once (D31). Bind a cache to a
// *sql.DB, never a transaction.
func (q *Queries) WithCache(cache *rt.StmtCache) *Queries {
	return &Queries{db: q.db, cache: cache}
}

// WithTx returns a copy of q running on tx. The statement cache does not
// follow: its statements are prepared on the outer handle (D31).
func (q *Queries) WithTx(tx *sql.Tx) *Queries { return &Queries{db: tx} }

// Tx runs fn inside a transaction: the Queries handed to fn joins it, a
// nil error commits, anything else rolls back. q must be backed by a
// handle that can begin a transaction (a *sql.DB).
func (q *Queries) Tx(ctx context.Context, fn func(*Queries) error) error {
	return rt.Tx(ctx, q.db, func(tx *sql.Tx) error { return fn(q.WithTx(tx)) })
}

// rowScanner is the shared surface of *sql.Row and *sql.Rows.
type rowScanner interface {
	Scan(dest ...any) error
}

// userScan reads one users row in generated column order.
func userScan(r rowScanner) (User, error) {
	var v User
	err := r.Scan(&v.ID, &v.Email)
	return v, err
}

const userGetSQL = `SELECT "id", "email" FROM "users" WHERE "id" = :id`

// UserGet fetches the users row with the given primary key, or rt.ErrNotFound.
func (q *Queries) UserGet(ctx context.Context, id int32) (User, error) {
	return userScan(q.db.QueryRowContext(ctx, userGetSQL, sql.Named("id", id)))
}

const userGetManySQL = `SELECT "id", "email" FROM "users" WHERE "id" IN`

// UserGetMany fetches the users rows whose primary key is in ids, in
// database order. Missing keys are not an error; they are just absent.
func (q *Queries) UserGetMany(ctx context.Context, ids []int32) ([]User, error) {
	if len(ids) == 0 {
		return nil, nil
	}
	args := make([]any, len(ids))
	for i, k := range ids {
		args[i] = k
	}
	query := userGetManySQL + " (?" + strings.Repeat(", ?", len(ids)-1) + ")"
	rows, err := q.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []User{}
	for rows.Next() {
		v, err := userScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

const userGetByEmailSQL = `SELECT "id", "email" FROM "users" WHERE "email" = :email`

// UserGetByEmail fetches the users row with the given email (a unique column),
// or rt.ErrNotFound.
func (q *Queries) UserGetByEmail(ctx context.Context, email string) (User, error) {
	return userScan(q.db.QueryRowContext(ctx, userGetByEmailSQL, sql.Named("email", email)))
}

const userListSQL = `SELECT "id", "email" FROM "users"`

// UserList returns every users row.
func (q *Queries) UserList(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, userListSQL)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []User{}
	for rows.Next() {
		v, err := userScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

const userCreateSQL = `INSERT INTO "users" ("email") VALUES (:email) RETURNING "id", "email"`

// UserCreateParams are the caller-supplied columns of UserCreate. The
// auto-increment key and defaulted columns are the database's job (D16).
type UserCreateParams struct {
	Email string `db:"email" json:"email"`
}

// UserCreate inserts a users row and returns the row the database wrote,
// generated keys and defaults filled in.
func (q *Queries) UserCreate(ctx context.Context, arg UserCreateParams) (User, error) {
	return userScan(q.db.QueryRowContext(ctx, userCreateSQL,
		sql.Named("email", arg.Email),
	))
}

const userUpdateSQL = `UPDATE "users" SET "email" = :email WHERE "id" = :id RETURNING "id", "email"`

// UserUpdateParams are the data columns of UserUpdate: every column
// outside the primary key.
type UserUpdateParams struct {
	Email string `db:"email" json:"email"`
}

// UserUpdate rewrites every non-key column of the identified users row
// and returns the result, or rt.ErrNotFound when no row matches.
func (q *Queries) UserUpdate(ctx context.Context, id int32, arg UserUpdateParams) (User, error) {
	return userScan(q.db.QueryRowContext(ctx, userUpdateSQL,
		sql.Named("id", id),
		sql.Named("email", arg.Email),
	))
}

const userDeleteSQL = `DELETE FROM "users" WHERE "id" = :id`

// UserDelete removes the identified users row; rt.ErrNotFound reports
// that nothing matched.
func (q *Queries) UserDelete(ctx context.Context, id int32) error {
	res, err := q.db.ExecContext(ctx, userDeleteSQL, sql.Named("id", id))
	if err != nil {
		return err
	}
	n, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if n == 0 {
		return rt.ErrNotFound
	}
	return nil
}

// msRevenueScan reads one ms_revenue row in generated column order.
func msRevenueScan(r rowScanner) (MsRevenue, error) {
	var v MsRevenue
	err := r.Scan(&v.ID, &v.Org, &v.Year)
	return v, err
}

const msRevenueGetSQL = `SELECT "id", "org", "year" FROM "ms_revenue" WHERE "id" = :id`

// MsRevenueGet fetches the ms_revenue row with the given primary key, or rt.ErrNotFound.
func (q *Queries) MsRevenueGet(ctx context.Context, id int32) (MsRevenue, error) {
	return msRevenueScan(q.db.QueryRowContext(ctx, msRevenueGetSQL, sql.Named("id", id)))
}

const msRevenueGetManySQL = `SELECT "id", "org", "year" FROM "ms_revenue" WHERE "id" IN`

// MsRevenueGetMany fetches the ms_revenue rows whose primary key is in ids, in
// database order. Missing keys are not an error; they are just absent.
func (q *Queries) MsRevenueGetMany(ctx context.Context, ids []int32) ([]MsRevenue, error) {
	if len(ids) == 0 {
		return nil, nil
	}
	args := make([]any, len(ids))
	for i, k := range ids {
		args[i] = k
	}
	query := msRevenueGetManySQL + " (?" + strings.Repeat(", ?", len(ids)-1) + ")"
	rows, err := q.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []MsRevenue{}
	for rows.Next() {
		v, err := msRevenueScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

const msRevenueListSQL = `SELECT "id", "org", "year" FROM "ms_revenue"`

// MsRevenueList returns every ms_revenue row.
func (q *Queries) MsRevenueList(ctx context.Context) ([]MsRevenue, error) {
	rows, err := q.db.QueryContext(ctx, msRevenueListSQL)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []MsRevenue{}
	for rows.Next() {
		v, err := msRevenueScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

const msRevenueCreateSQL = `INSERT INTO "ms_revenue" ("org", "year") VALUES (:org, :year) RETURNING "id", "org", "year"`

// MsRevenueCreateParams are the caller-supplied columns of MsRevenueCreate. The
// auto-increment key and defaulted columns are the database's job (D16).
type MsRevenueCreateParams struct {
	Org  string `db:"org" json:"org"`
	Year int32  `db:"year" json:"year"`
}

// MsRevenueCreate inserts a ms_revenue row and returns the row the database wrote,
// generated keys and defaults filled in.
func (q *Queries) MsRevenueCreate(ctx context.Context, arg MsRevenueCreateParams) (MsRevenue, error) {
	return msRevenueScan(q.db.QueryRowContext(ctx, msRevenueCreateSQL,
		sql.Named("org", arg.Org),
		sql.Named("year", arg.Year),
	))
}

const msRevenueUpdateSQL = `UPDATE "ms_revenue" SET "org" = :org, "year" = :year WHERE "id" = :id RETURNING "id", "org", "year"`

// MsRevenueUpdateParams are the data columns of MsRevenueUpdate: every column
// outside the primary key.
type MsRevenueUpdateParams struct {
	Org  string `db:"org" json:"org"`
	Year int32  `db:"year" json:"year"`
}

// MsRevenueUpdate rewrites every non-key column of the identified ms_revenue row
// and returns the result, or rt.ErrNotFound when no row matches.
func (q *Queries) MsRevenueUpdate(ctx context.Context, id int32, arg MsRevenueUpdateParams) (MsRevenue, error) {
	return msRevenueScan(q.db.QueryRowContext(ctx, msRevenueUpdateSQL,
		sql.Named("id", id),
		sql.Named("org", arg.Org),
		sql.Named("year", arg.Year),
	))
}

const msRevenueDeleteSQL = `DELETE FROM "ms_revenue" WHERE "id" = :id`

// MsRevenueDelete removes the identified ms_revenue row; rt.ErrNotFound reports
// that nothing matched.
func (q *Queries) MsRevenueDelete(ctx context.Context, id int32) error {
	res, err := q.db.ExecContext(ctx, msRevenueDeleteSQL, sql.Named("id", id))
	if err != nil {
		return err
	}
	n, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if n == 0 {
		return rt.ErrNotFound
	}
	return nil
}

// msUsageScan reads one ms_usage row in generated column order.
func msUsageScan(r rowScanner) (MsUsage, error) {
	var v MsUsage
	err := r.Scan(&v.ID, &v.Org, &v.Year)
	return v, err
}

const msUsageGetSQL = `SELECT "id", "org", "year" FROM "ms_usage" WHERE "id" = :id`

// MsUsageGet fetches the ms_usage row with the given primary key, or rt.ErrNotFound.
func (q *Queries) MsUsageGet(ctx context.Context, id int32) (MsUsage, error) {
	return msUsageScan(q.db.QueryRowContext(ctx, msUsageGetSQL, sql.Named("id", id)))
}

const msUsageGetManySQL = `SELECT "id", "org", "year" FROM "ms_usage" WHERE "id" IN`

// MsUsageGetMany fetches the ms_usage rows whose primary key is in ids, in
// database order. Missing keys are not an error; they are just absent.
func (q *Queries) MsUsageGetMany(ctx context.Context, ids []int32) ([]MsUsage, error) {
	if len(ids) == 0 {
		return nil, nil
	}
	args := make([]any, len(ids))
	for i, k := range ids {
		args[i] = k
	}
	query := msUsageGetManySQL + " (?" + strings.Repeat(", ?", len(ids)-1) + ")"
	rows, err := q.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []MsUsage{}
	for rows.Next() {
		v, err := msUsageScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

const msUsageListSQL = `SELECT "id", "org", "year" FROM "ms_usage"`

// MsUsageList returns every ms_usage row.
func (q *Queries) MsUsageList(ctx context.Context) ([]MsUsage, error) {
	rows, err := q.db.QueryContext(ctx, msUsageListSQL)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []MsUsage{}
	for rows.Next() {
		v, err := msUsageScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

const msUsageCreateSQL = `INSERT INTO "ms_usage" ("org", "year") VALUES (:org, :year) RETURNING "id", "org", "year"`

// MsUsageCreateParams are the caller-supplied columns of MsUsageCreate. The
// auto-increment key and defaulted columns are the database's job (D16).
type MsUsageCreateParams struct {
	Org  string `db:"org" json:"org"`
	Year int32  `db:"year" json:"year"`
}

// MsUsageCreate inserts a ms_usage row and returns the row the database wrote,
// generated keys and defaults filled in.
func (q *Queries) MsUsageCreate(ctx context.Context, arg MsUsageCreateParams) (MsUsage, error) {
	return msUsageScan(q.db.QueryRowContext(ctx, msUsageCreateSQL,
		sql.Named("org", arg.Org),
		sql.Named("year", arg.Year),
	))
}

const msUsageUpdateSQL = `UPDATE "ms_usage" SET "org" = :org, "year" = :year WHERE "id" = :id RETURNING "id", "org", "year"`

// MsUsageUpdateParams are the data columns of MsUsageUpdate: every column
// outside the primary key.
type MsUsageUpdateParams struct {
	Org  string `db:"org" json:"org"`
	Year int32  `db:"year" json:"year"`
}

// MsUsageUpdate rewrites every non-key column of the identified ms_usage row
// and returns the result, or rt.ErrNotFound when no row matches.
func (q *Queries) MsUsageUpdate(ctx context.Context, id int32, arg MsUsageUpdateParams) (MsUsage, error) {
	return msUsageScan(q.db.QueryRowContext(ctx, msUsageUpdateSQL,
		sql.Named("id", id),
		sql.Named("org", arg.Org),
		sql.Named("year", arg.Year),
	))
}

const msUsageDeleteSQL = `DELETE FROM "ms_usage" WHERE "id" = :id`

// MsUsageDelete removes the identified ms_usage row; rt.ErrNotFound reports
// that nothing matched.
func (q *Queries) MsUsageDelete(ctx context.Context, id int32) error {
	res, err := q.db.ExecContext(ctx, msUsageDeleteSQL, sql.Named("id", id))
	if err != nil {
		return err
	}
	n, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if n == 0 {
		return rt.ErrNotFound
	}
	return nil
}
