// Code generated by nao gen from package itest/blog/db; DO NOT EDIT.
//
// Selects declared in the schema (docs/spec.md §V11): one method per
// group member, statically typed, prepare-validated.

package db

import (
	"context"
	"database/sql"
	"github.com/Piechutowski/volt/nao/rt"
)

const userPickedSQL = `SELECT "id", "email" FROM "users" WHERE id IN (SELECT value FROM json_each(:ids)) ORDER BY id ASC`

// UserPicked runs the "picked" select over users (spec §V11).
func (q *Queries) UserPicked(ctx context.Context, ids []int32) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, userPickedSQL, sql.Named("ids", rt.JSONList(ids)))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []User{}
	for rows.Next() {
		v, err := userScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

const msRevenueBrowseSQL = `SELECT "id", "org", "year" FROM "ms_revenue" WHERE year = :year ORDER BY id ASC`

// MsRevenueBrowse runs the "browse" select over ms_revenue (spec §V11).
func (q *Queries) MsRevenueBrowse(ctx context.Context, year int32) ([]MsRevenue, error) {
	rows, err := q.db.QueryContext(ctx, msRevenueBrowseSQL, sql.Named("year", year))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []MsRevenue{}
	for rows.Next() {
		v, err := msRevenueScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

const msUsageBrowseSQL = `SELECT "id", "org", "year" FROM "ms_usage" WHERE year = :year ORDER BY id ASC`

// MsUsageBrowse runs the "browse" select over ms_usage (spec §V11).
func (q *Queries) MsUsageBrowse(ctx context.Context, year int32) ([]MsUsage, error) {
	rows, err := q.db.QueryContext(ctx, msUsageBrowseSQL, sql.Named("year", year))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []MsUsage{}
	for rows.Next() {
		v, err := msUsageScan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}
