-- Code generated by nao gen sqlite from package itest/blog/db; DO NOT EDIT.

PRAGMA foreign_keys = ON;

CREATE TABLE users (
  id INTEGER PRIMARY KEY,
  email TEXT NOT NULL UNIQUE
);

CREATE TABLE ms_revenue (
  id INTEGER PRIMARY KEY,
  org TEXT NOT NULL,
  year INTEGER NOT NULL
);

CREATE TABLE ms_usage (
  id INTEGER PRIMARY KEY,
  org TEXT NOT NULL,
  year INTEGER NOT NULL
);
