// Code generated by nao gen from package itest/blog/db; DO NOT EDIT.
//
// Validators for the schema's checks (docs/spec.md §V12): typed
// checks evaluate exactly like their SQL CHECK twins; Go-reference
// checks call hand-written functions of this package.

package db

import (
	"github.com/Piechutowski/volt/nao/rt"
)

// Validate evaluates every check of users against the row's values
// (spec §V12). Typed checks are also CHECK constraints in the DDL;
// Go-reference checks run here only — SQLite cannot call Go.
func (v User) Validate() error {
	var errs []rt.CheckError
	if !(rt.Like(v.Email, "%_@%_")) {
		errs = append(errs, rt.CheckError{Model: "User", Check: "email_shape"})
	}
	if err := EmailValid(v.Email); err != nil {
		errs = append(errs, rt.CheckError{Model: "User", Check: "EmailValid(email)", Cause: err})
	}
	return rt.Validation(errs)
}

// Validate evaluates the checks of users whose columns UserCreateParams carries
// (spec §V12.6).
func (v UserCreateParams) Validate() error {
	var errs []rt.CheckError
	if !(rt.Like(v.Email, "%_@%_")) {
		errs = append(errs, rt.CheckError{Model: "User", Check: "email_shape"})
	}
	if err := EmailValid(v.Email); err != nil {
		errs = append(errs, rt.CheckError{Model: "User", Check: "EmailValid(email)", Cause: err})
	}
	return rt.Validation(errs)
}

// Validate evaluates the checks of users whose columns UserUpdateParams carries
// (spec §V12.6).
func (v UserUpdateParams) Validate() error {
	var errs []rt.CheckError
	if !(rt.Like(v.Email, "%_@%_")) {
		errs = append(errs, rt.CheckError{Model: "User", Check: "email_shape"})
	}
	if err := EmailValid(v.Email); err != nil {
		errs = append(errs, rt.CheckError{Model: "User", Check: "EmailValid(email)", Cause: err})
	}
	return rt.Validation(errs)
}
