// Code generated by volt gen. DO NOT EDIT.
//
// Source: package itest/blog/app

package app

import (
	"net/http"

	"github.com/Piechutowski/volt"
)

// AdminController is implemented by your code and wired through
// Controllers; a route referencing Admin.<Action> will not build until
// the method exists with this exact signature.
type AdminController interface {
	// Stats handles GET /admin/stats
	Stats(w http.ResponseWriter, r *volt.Request) error
}

// ArchiveController is implemented by your code and wired through
// Controllers; a route referencing Archive.<Action> will not build until
// the method exists with this exact signature.
type ArchiveController interface {
	// Show handles GET /archive/:stamp(int64)
	Show(w http.ResponseWriter, r *volt.Request, stamp int64) error
}

// FilesController is implemented by your code and wired through
// Controllers; a route referencing Files.<Action> will not build until
// the method exists with this exact signature.
type FilesController interface {
	// Serve handles GET /files/:path...
	Serve(w http.ResponseWriter, r *volt.Request, path string) error
}

// HomeController is implemented by your code and wired through
// Controllers; a route referencing Home.<Action> will not build until
// the method exists with this exact signature.
type HomeController interface {
	// Index handles GET /
	Index(w http.ResponseWriter, r *volt.Request) error
	// Teapot handles GET /teapot
	Teapot(w http.ResponseWriter, r *volt.Request) error
	// Ping handles any /ping
	Ping(w http.ResponseWriter, r *volt.Request) error
}

// OpsController is implemented by your code and wired through
// Controllers; a route referencing Ops.<Action> will not build until
// the method exists with this exact signature.
type OpsController interface {
	// Fail handles GET /ops/fail
	Fail(w http.ResponseWriter, r *volt.Request) error
}

// PagesController is implemented by your code and wired through
// Controllers; a route referencing Pages.<Action> will not build until
// the method exists with this exact signature.
type PagesController interface {
	// Show handles GET /pages/:num(int)
	Show(w http.ResponseWriter, r *volt.Request, num int) error
}

// TagsController is implemented by your code and wired through
// Controllers; a route referencing Tags.<Action> will not build until
// the method exists with this exact signature.
type TagsController interface {
	// Show handles GET /tags/:name
	Show(w http.ResponseWriter, r *volt.Request, name string) error
}

// UsersController is implemented by your code and wired through
// Controllers; a route referencing Users.<Action> will not build until
// the method exists with this exact signature.
type UsersController interface {
	// Index handles GET /users
	Index(w http.ResponseWriter, r *volt.Request) error
	// New handles GET /users/new
	New(w http.ResponseWriter, r *volt.Request) error
	// Create handles POST /users
	Create(w http.ResponseWriter, r *volt.Request) error
	// Show handles GET /users/:id(int32)
	Show(w http.ResponseWriter, r *volt.Request, id int32) error
	// Edit handles GET /users/:id(int32)/edit
	Edit(w http.ResponseWriter, r *volt.Request, id int32) error
	// Update handles PATCH /users/:id(int32)
	// Update handles PUT /users/:id(int32)
	Update(w http.ResponseWriter, r *volt.Request, id int32) error
	// Delete handles DELETE /users/:id(int32)
	Delete(w http.ResponseWriter, r *volt.Request, id int32) error
	// Avatar handles GET /users/:id(int32)/avatar
	Avatar(w http.ResponseWriter, r *volt.Request, id int32) error
}

// Controllers is the dependency manifest of the route table: one
// implementation per controller named in the routes.
type Controllers struct {
	Admin   AdminController
	Archive ArchiveController
	Files   FilesController
	Home    HomeController
	Ops     OpsController
	Pages   PagesController
	Tags    TagsController
	Users   UsersController
}

// New builds the router: ServeMux registrations with statically
// composed pipelines. The result is a plain http.Handler.
func New(c Controllers) http.Handler {
	mux := http.NewServeMux()
	register(mux, c)
	return mux
}
