// Code generated by volt gen. DO NOT EDIT.
//
// Source: package itest/blog/app

package app

import (
	"github.com/Piechutowski/volt"
)

// PathRoot returns the path for GET / (Home.Index).
func PathRoot(opts ...volt.URLOption) string {
	return volt.URL("/", opts...)
}

// PathTeapot returns the path for GET /teapot (Home.Teapot).
func PathTeapot(opts ...volt.URLOption) string {
	return volt.URL("/teapot", opts...)
}

// PathPing returns the path for any /ping (Home.Ping).
func PathPing(opts ...volt.URLOption) string {
	return volt.URL("/ping", opts...)
}

// PathAdminStats returns the path for GET /admin/stats (Admin.Stats).
func PathAdminStats(opts ...volt.URLOption) string {
	return volt.URL("/admin/stats", opts...)
}

// PathOpsFail returns the path for GET /ops/fail (Ops.Fail).
func PathOpsFail(opts ...volt.URLOption) string {
	return volt.URL("/ops/fail", opts...)
}

// PathUsers returns the path for GET /users (Users.Index).
func PathUsers(opts ...volt.URLOption) string {
	return volt.URL("/users", opts...)
}

// PathNewUser returns the path for GET /users/new (Users.New).
func PathNewUser(opts ...volt.URLOption) string {
	return volt.URL("/users/new", opts...)
}

// PathUser returns the path for GET /users/:id(int32) (Users.Show).
func PathUser(id int32, opts ...volt.URLOption) string {
	return volt.URL("/users/"+volt.SegInt(int64(id)), opts...)
}

// PathEditUser returns the path for GET /users/:id(int32)/edit (Users.Edit).
func PathEditUser(id int32, opts ...volt.URLOption) string {
	return volt.URL("/users/"+volt.SegInt(int64(id))+"/edit", opts...)
}

// PathAvatar returns the path for GET /users/:id(int32)/avatar (Users.Avatar).
func PathAvatar(id int32, opts ...volt.URLOption) string {
	return volt.URL("/users/"+volt.SegInt(int64(id))+"/avatar", opts...)
}

// PathServe returns the path for GET /files/:path... (Files.Serve).
func PathServe(path string, opts ...volt.URLOption) string {
	return volt.URL("/files/"+volt.SegWild(path), opts...)
}

// PathTag returns the path for GET /tags/:name (Tags.Show).
func PathTag(name string, opts ...volt.URLOption) string {
	return volt.URL("/tags/"+volt.Seg(name), opts...)
}

// PathPage returns the path for GET /pages/:num(int) (Pages.Show).
func PathPage(num int, opts ...volt.URLOption) string {
	return volt.URL("/pages/"+volt.SegInt(int64(num)), opts...)
}

// PathArchive returns the path for GET /archive/:stamp(int64) (Archive.Show).
func PathArchive(stamp int64, opts ...volt.URLOption) string {
	return volt.URL("/archive/"+volt.SegInt(stamp), opts...)
}

// PathAPIUserList returns the path for GET /api/users (db.UserList).
func PathAPIUserList(opts ...volt.URLOption) string {
	return volt.URL("/api/users", opts...)
}

// PathAPIUserGet returns the path for GET /api/users/:id(int32) (db.UserGet).
func PathAPIUserGet(id int32, opts ...volt.URLOption) string {
	return volt.URL("/api/users/"+volt.SegInt(int64(id)), opts...)
}

// PathAPIUserPicked returns the path for GET /api/picked (db.UserPicked).
func PathAPIUserPicked(opts ...volt.URLOption) string {
	return volt.URL("/api/picked", opts...)
}

// PathMsRevenueBrowse returns the path for GET /ms/revenue (db.MsRevenueBrowse).
func PathMsRevenueBrowse(opts ...volt.URLOption) string {
	return volt.URL("/ms/revenue", opts...)
}

// PathMsUsageBrowse returns the path for GET /ms/usage (db.MsUsageBrowse).
func PathMsUsageBrowse(opts ...volt.URLOption) string {
	return volt.URL("/ms/usage", opts...)
}

// PathEvents returns the path for GET /events (volt.Events).
func PathEvents(opts ...volt.URLOption) string {
	return volt.URL("/events", opts...)
}
