// Code generated by volt gen. DO NOT EDIT.
//
// Source: package app

package app

import (
	"net/http"

	"github.com/Piechutowski/volt"
)

// register wires every route of the package onto mux. Dispatch is
// decided here, at generation time: the route line and the call it
// makes are emitted together and cannot disagree.
func register(mux *http.ServeMux, c Controllers) {
	// pipeline api: volt.RequestID, TagOuter, TagInner
	pipe0 := func(h http.Handler) http.Handler {
		return volt.Chain(h, volt.RequestID, TagOuter, TagInner)
	}
	// pipeline api + extra: volt.RequestID, TagOuter, TagInner, TagExtra
	pipe1 := func(h http.Handler) http.Handler {
		return volt.Chain(h, volt.RequestID, TagOuter, TagInner, TagExtra)
	}

	// GET / → Home.Index [pipe: api]
	mux.Handle("GET /{$}", pipe0(volt.Handler("GET /{$}", func(w http.ResponseWriter, r *volt.Request) error {
		return c.Home.Index(w, r)
	}, errHandlerErrors)))

	// GET /teapot → Home.Teapot [pipe: api]
	mux.Handle("GET /teapot", pipe0(volt.Handler("GET /teapot", func(w http.ResponseWriter, r *volt.Request) error {
		return c.Home.Teapot(w, r)
	}, errHandlerErrors)))

	// any /ping → Home.Ping [pipe: api]
	mux.Handle("/ping", pipe0(volt.Handler("/ping", func(w http.ResponseWriter, r *volt.Request) error {
		return c.Home.Ping(w, r)
	}, errHandlerErrors)))

	// GET /admin/stats → Admin.Stats [pipe: api, extra]
	mux.Handle("GET /admin/stats", pipe1(volt.Handler("GET /admin/stats", func(w http.ResponseWriter, r *volt.Request) error {
		return c.Admin.Stats(w, r)
	}, errHandlerErrors)))

	// GET /ops/fail → Ops.Fail [pipe: api]
	mux.Handle("GET /ops/fail", pipe0(volt.Handler("GET /ops/fail", func(w http.ResponseWriter, r *volt.Request) error {
		return c.Ops.Fail(w, r)
	}, errHandlerOpsErrors)))

	// GET /users → Users.Index [pipe: api]
	mux.Handle("GET /users", pipe0(volt.Handler("GET /users", func(w http.ResponseWriter, r *volt.Request) error {
		return c.Users.Index(w, r)
	}, errHandlerErrors)))

	// GET /users/new → Users.New [pipe: api]
	mux.Handle("GET /users/new", pipe0(volt.Handler("GET /users/new", func(w http.ResponseWriter, r *volt.Request) error {
		return c.Users.New(w, r)
	}, errHandlerErrors)))

	// POST /users → Users.Create [pipe: api]
	mux.Handle("POST /users", pipe0(volt.Handler("POST /users", func(w http.ResponseWriter, r *volt.Request) error {
		return c.Users.Create(w, r)
	}, errHandlerErrors)))

	// GET /users/:id(int32) → Users.Show [pipe: api]
	mux.Handle("GET /users/{id}", pipe0(volt.Handler("GET /users/{id}", func(w http.ResponseWriter, r *volt.Request) error {
		voltid, ok := volt.ParseInt32(r.PathValue("id"))
		if !ok {
			return volt.ErrNotFound
		}
		return c.Users.Show(w, r, voltid)
	}, errHandlerErrors)))

	// GET /users/:id(int32)/edit → Users.Edit [pipe: api]
	mux.Handle("GET /users/{id}/edit", pipe0(volt.Handler("GET /users/{id}/edit", func(w http.ResponseWriter, r *volt.Request) error {
		voltid, ok := volt.ParseInt32(r.PathValue("id"))
		if !ok {
			return volt.ErrNotFound
		}
		return c.Users.Edit(w, r, voltid)
	}, errHandlerErrors)))

	// PATCH /users/:id(int32) → Users.Update [pipe: api]
	mux.Handle("PATCH /users/{id}", pipe0(volt.Handler("PATCH /users/{id}", func(w http.ResponseWriter, r *volt.Request) error {
		voltid, ok := volt.ParseInt32(r.PathValue("id"))
		if !ok {
			return volt.ErrNotFound
		}
		return c.Users.Update(w, r, voltid)
	}, errHandlerErrors)))

	// PUT /users/:id(int32) → Users.Update [pipe: api]
	mux.Handle("PUT /users/{id}", pipe0(volt.Handler("PUT /users/{id}", func(w http.ResponseWriter, r *volt.Request) error {
		voltid, ok := volt.ParseInt32(r.PathValue("id"))
		if !ok {
			return volt.ErrNotFound
		}
		return c.Users.Update(w, r, voltid)
	}, errHandlerErrors)))

	// DELETE /users/:id(int32) → Users.Delete [pipe: api]
	mux.Handle("DELETE /users/{id}", pipe0(volt.Handler("DELETE /users/{id}", func(w http.ResponseWriter, r *volt.Request) error {
		voltid, ok := volt.ParseInt32(r.PathValue("id"))
		if !ok {
			return volt.ErrNotFound
		}
		return c.Users.Delete(w, r, voltid)
	}, errHandlerErrors)))

	// GET /users/:id(int32)/avatar → Users.Avatar [pipe: api]
	mux.Handle("GET /users/{id}/avatar", pipe0(volt.Handler("GET /users/{id}/avatar", func(w http.ResponseWriter, r *volt.Request) error {
		voltid, ok := volt.ParseInt32(r.PathValue("id"))
		if !ok {
			return volt.ErrNotFound
		}
		return c.Users.Avatar(w, r, voltid)
	}, errHandlerErrors)))

	// GET /files/:path... → Files.Serve [pipe: api]
	mux.Handle("GET /files/{path...}", pipe0(volt.Handler("GET /files/{path...}", func(w http.ResponseWriter, r *volt.Request) error {
		return c.Files.Serve(w, r, r.PathValue("path"))
	}, errHandlerErrors)))

	// GET /tags/:name → Tags.Show [pipe: api]
	mux.Handle("GET /tags/{name}", pipe0(volt.Handler("GET /tags/{name}", func(w http.ResponseWriter, r *volt.Request) error {
		return c.Tags.Show(w, r, r.PathValue("name"))
	}, errHandlerErrors)))

	// GET /pages/:num(int) → Pages.Show [pipe: api]
	mux.Handle("GET /pages/{num}", pipe0(volt.Handler("GET /pages/{num}", func(w http.ResponseWriter, r *volt.Request) error {
		voltnum, ok := volt.ParseInt(r.PathValue("num"))
		if !ok {
			return volt.ErrNotFound
		}
		return c.Pages.Show(w, r, voltnum)
	}, errHandlerErrors)))

	// GET /archive/:stamp(int64) → Archive.Show [pipe: api]
	mux.Handle("GET /archive/{stamp}", pipe0(volt.Handler("GET /archive/{stamp}", func(w http.ResponseWriter, r *volt.Request) error {
		voltstamp, ok := volt.ParseInt64(r.PathValue("stamp"))
		if !ok {
			return volt.ErrNotFound
		}
		return c.Archive.Show(w, r, voltstamp)
	}, errHandlerErrors)))
}

// errHandlerErrors adapts the error_handler declared in the routes.
var errHandlerErrors = volt.ErrorHandler(Errors)

// errHandlerOpsErrors adapts the error_handler declared in the routes.
var errHandlerOpsErrors = volt.ErrorHandler(OpsErrors)
