// Code generated by volt gen. DO NOT EDIT.
//
// Source: package itest/blog/app

package app

import (
	"github.com/Piechutowski/volt"
)

// Table lists every route of the package, in declaration order:
// the routing DSL as introspectable data ('volt routes', metrics
// labels, and downstream derivations read this).
var Table = []volt.Route{
	{Method: "GET", Pattern: "/{$}", Spelled: "/", Controller: "Home", Action: "Index", Helper: "PathRoot"},
	{Method: "GET", Pattern: "/teapot", Spelled: "/teapot", Controller: "Home", Action: "Teapot", Helper: "PathTeapot"},
	{Method: "", Pattern: "/ping", Spelled: "/ping", Controller: "Home", Action: "Ping", Helper: "PathPing"},
	{Method: "GET", Pattern: "/admin/stats", Spelled: "/admin/stats", Controller: "Admin", Action: "Stats", Helper: "PathAdminStats"},
	{Method: "GET", Pattern: "/ops/fail", Spelled: "/ops/fail", Controller: "Ops", Action: "Fail", Helper: "PathOpsFail"},
	{Method: "GET", Pattern: "/users", Spelled: "/users", Controller: "Users", Action: "Index", Helper: "PathUsers"},
	{Method: "GET", Pattern: "/users/new", Spelled: "/users/new", Controller: "Users", Action: "New", Helper: "PathNewUser"},
	{Method: "POST", Pattern: "/users", Spelled: "/users", Controller: "Users", Action: "Create"},
	{Method: "GET", Pattern: "/users/{id}", Spelled: "/users/:id(int32)", Controller: "Users", Action: "Show", Helper: "PathUser", Params: []volt.RouteParam{{Name: "id", Type: "int32"}}},
	{Method: "GET", Pattern: "/users/{id}/edit", Spelled: "/users/:id(int32)/edit", Controller: "Users", Action: "Edit", Helper: "PathEditUser", Params: []volt.RouteParam{{Name: "id", Type: "int32"}}},
	{Method: "PATCH", Pattern: "/users/{id}", Spelled: "/users/:id(int32)", Controller: "Users", Action: "Update", Params: []volt.RouteParam{{Name: "id", Type: "int32"}}},
	{Method: "PUT", Pattern: "/users/{id}", Spelled: "/users/:id(int32)", Controller: "Users", Action: "Update", Params: []volt.RouteParam{{Name: "id", Type: "int32"}}},
	{Method: "DELETE", Pattern: "/users/{id}", Spelled: "/users/:id(int32)", Controller: "Users", Action: "Delete", Params: []volt.RouteParam{{Name: "id", Type: "int32"}}},
	{Method: "GET", Pattern: "/users/{id}/avatar", Spelled: "/users/:id(int32)/avatar", Controller: "Users", Action: "Avatar", Helper: "PathAvatar", Params: []volt.RouteParam{{Name: "id", Type: "int32"}}},
	{Method: "GET", Pattern: "/files/{path...}", Spelled: "/files/:path...", Controller: "Files", Action: "Serve", Helper: "PathServe", Params: []volt.RouteParam{{Name: "path", Type: "string", Wild: true}}},
	{Method: "GET", Pattern: "/tags/{name}", Spelled: "/tags/:name", Controller: "Tags", Action: "Show", Helper: "PathTag", Params: []volt.RouteParam{{Name: "name", Type: "string"}}},
	{Method: "GET", Pattern: "/pages/{num}", Spelled: "/pages/:num(int)", Controller: "Pages", Action: "Show", Helper: "PathPage", Params: []volt.RouteParam{{Name: "num", Type: "int"}}},
	{Method: "GET", Pattern: "/archive/{stamp}", Spelled: "/archive/:stamp(int64)", Controller: "Archive", Action: "Show", Helper: "PathArchive", Params: []volt.RouteParam{{Name: "stamp", Type: "int64"}}},
}
