// Code generated by volt gen. DO NOT EDIT.
// (Illustrative — hand-written to show what `volt gen` will emit.)
package app

import (
	"net/http"

	"github.com/Piechutowski/volt"
	"github.com/Piechutowski/volt/dataset"

	"example.com/metrics/db"
)

// One interface per controller named in routes.volt. Implement them
// anywhere — satisfaction is implicit; forgetting one is a compile error.

type HealthController interface {
	Check(w http.ResponseWriter, r *volt.Request) error
}

// AppController exists because routes.volt overrides ms_revenue's list
// with App.MsRevenueList. The `next` parameter is the generated default
// for this operation: call it to wrap, ignore it to replace.
type AppController interface {
	MsRevenueList(w http.ResponseWriter, r *volt.Request, q volt.GridQuery,
		next dataset.ListFunc[db.MsRevenue]) error
}

// Controllers is the dependency manifest of the whole route table.
type Controllers struct {
	Health HealthController
	App    AppController
}

// New builds the router: ServeMux registrations, statically composed
// pipelines, dataset wiring. The only public entry point.
func New(c Controllers, opts ...volt.Option) http.Handler {
	deps := volt.BuildDeps(opts...)
	mux := http.NewServeMux()
	registerRoutes(mux, c, deps)    // volt_router.go (not shown)
	registerDatasetMS(mux, c, deps) // volt_dataset_ms.go
	return mux
}
