// Code generated by volt gen. DO NOT EDIT.
// (Illustrative — hand-written to show what `volt gen` will emit.)
package app

import "github.com/Piechutowski/volt"

// Typed reverse URLs. A helper that doesn't exist, or is called with the
// wrong argument types, does not compile (R5).

func PathHealth(opts ...volt.URLOption) string    { return volt.Path("/health", opts...) }
func PathMsRevenue(opts ...volt.URLOption) string { return volt.Path("/ms/revenue", opts...) }
func PathMsRevenueRow(id int64, opts ...volt.URLOption) string {
	return volt.PathID("/ms/revenue/", id, opts...)
}
func PathMsUsage(opts ...volt.URLOption) string { return volt.Path("/ms/usage", opts...) }
func PathMsUsageRow(id int64, opts ...volt.URLOption) string {
	return volt.PathID("/ms/usage/", id, opts...)
}
func PathMsMeta(opts ...volt.URLOption) string { return volt.Path("/ms/_meta", opts...) }
