// Code generated by volt gen. DO NOT EDIT.
// (Illustrative — hand-written to show what `volt gen` will emit.)
package app

import "github.com/Piechutowski/volt"

// Typed reverse URLs. A helper that doesn't exist, or is called with the
// wrong argument types, does not compile (R5).

func PathHealth(opts ...volt.URLOption) string { return volt.Path("/health", opts...) }
func PathDaRR(opts ...volt.URLOption) string   { return volt.Path("/da/r_r", opts...) }
func PathDaRRRow(idpk int64, opts ...volt.URLOption) string {
	return volt.PathID("/da/r_r/", idpk, opts...)
}
func PathDaIU(opts ...volt.URLOption) string { return volt.Path("/da/i_u", opts...) }
func PathDaIURow(idpk int64, opts ...volt.URLOption) string {
	return volt.PathID("/da/i_u/", idpk, opts...)
}
func PathDaMeta(opts ...volt.URLOption) string { return volt.Path("/da/_meta", opts...) }
