// Code generated by volt gen. DO NOT EDIT.
//
// Source: package app

package app

import (
	"net/http"

	"github.com/Piechutowski/volt"
)

// CommentsController is implemented by your code and wired through
// Controllers; a route referencing Comments.<Action> will not build until
// the method exists with this exact signature.
type CommentsController interface {
	// Index handles GET /api/comments
	Index(w http.ResponseWriter, r *volt.Request) error
	// Create handles POST /api/comments
	Create(w http.ResponseWriter, r *volt.Request) error
	// Show handles GET /api/comments/:id(int32)
	Show(w http.ResponseWriter, r *volt.Request, id int32) error
	// Update handles PATCH /api/comments/:id(int32)
	// Update handles PUT /api/comments/:id(int32)
	Update(w http.ResponseWriter, r *volt.Request, id int32) error
}

// HealthController is implemented by your code and wired through
// Controllers; a route referencing Health.<Action> will not build until
// the method exists with this exact signature.
type HealthController interface {
	// Check handles GET /health
	Check(w http.ResponseWriter, r *volt.Request) error
}

// PostsController is implemented by your code and wired through
// Controllers; a route referencing Posts.<Action> will not build until
// the method exists with this exact signature.
type PostsController interface {
	// Index handles GET /posts
	Index(w http.ResponseWriter, r *volt.Request) error
	// New handles GET /posts/new
	New(w http.ResponseWriter, r *volt.Request) error
	// Create handles POST /posts
	Create(w http.ResponseWriter, r *volt.Request) error
	// Show handles GET /posts/:id(int32)
	Show(w http.ResponseWriter, r *volt.Request, id int32) error
	// Edit handles GET /posts/:id(int32)/edit
	Edit(w http.ResponseWriter, r *volt.Request, id int32) error
	// Update handles PATCH /posts/:id(int32)
	// Update handles PUT /posts/:id(int32)
	Update(w http.ResponseWriter, r *volt.Request, id int32) error
	// Delete handles DELETE /posts/:id(int32)
	Delete(w http.ResponseWriter, r *volt.Request, id int32) error
}

// Controllers is the dependency manifest of the route table: one
// implementation per controller named in the routes.
type Controllers struct {
	Comments CommentsController
	Health   HealthController
	Posts    PostsController
}

// New builds the router: ServeMux registrations with statically
// composed pipelines. The result is a plain http.Handler.
func New(c Controllers) http.Handler {
	mux := http.NewServeMux()
	register(mux, c)
	return mux
}
