// Code generated by volt gen. DO NOT EDIT.
//
// Source: package app

package app

import (
	"net/http"

	"github.com/Piechutowski/volt"
)

// register wires every route of the package onto mux. Dispatch is
// decided here, at generation time: the route line and the call it
// makes are emitted together and cannot disagree.
func register(mux *http.ServeMux, c Controllers) {
	// pipeline api: volt.RequestID
	pipe0 := func(h http.Handler) http.Handler {
		return volt.Chain(h, volt.RequestID)
	}

	// GET /health → Health.Check [pipe: api]
	mux.Handle("GET /health", pipe0(volt.Handler("GET /health", func(w http.ResponseWriter, r *volt.Request) error {
		return c.Health.Check(w, r)
	}, errHandlerErrors)))

	// GET /posts → Posts.Index [pipe: api]
	mux.Handle("GET /posts", pipe0(volt.Handler("GET /posts", func(w http.ResponseWriter, r *volt.Request) error {
		return c.Posts.Index(w, r)
	}, errHandlerErrors)))

	// GET /posts/new → Posts.New [pipe: api]
	mux.Handle("GET /posts/new", pipe0(volt.Handler("GET /posts/new", func(w http.ResponseWriter, r *volt.Request) error {
		return c.Posts.New(w, r)
	}, errHandlerErrors)))

	// POST /posts → Posts.Create [pipe: api]
	mux.Handle("POST /posts", pipe0(volt.Handler("POST /posts", func(w http.ResponseWriter, r *volt.Request) error {
		return c.Posts.Create(w, r)
	}, errHandlerErrors)))

	// GET /posts/:id(int32) → Posts.Show [pipe: api]
	mux.Handle("GET /posts/{id}", pipe0(volt.Handler("GET /posts/{id}", func(w http.ResponseWriter, r *volt.Request) error {
		voltid, ok := volt.ParseInt32(r.PathValue("id"))
		if !ok {
			return volt.ErrNotFound
		}
		return c.Posts.Show(w, r, voltid)
	}, errHandlerErrors)))

	// GET /posts/:id(int32)/edit → Posts.Edit [pipe: api]
	mux.Handle("GET /posts/{id}/edit", pipe0(volt.Handler("GET /posts/{id}/edit", func(w http.ResponseWriter, r *volt.Request) error {
		voltid, ok := volt.ParseInt32(r.PathValue("id"))
		if !ok {
			return volt.ErrNotFound
		}
		return c.Posts.Edit(w, r, voltid)
	}, errHandlerErrors)))

	// PATCH /posts/:id(int32) → Posts.Update [pipe: api]
	mux.Handle("PATCH /posts/{id}", pipe0(volt.Handler("PATCH /posts/{id}", func(w http.ResponseWriter, r *volt.Request) error {
		voltid, ok := volt.ParseInt32(r.PathValue("id"))
		if !ok {
			return volt.ErrNotFound
		}
		return c.Posts.Update(w, r, voltid)
	}, errHandlerErrors)))

	// PUT /posts/:id(int32) → Posts.Update [pipe: api]
	mux.Handle("PUT /posts/{id}", pipe0(volt.Handler("PUT /posts/{id}", func(w http.ResponseWriter, r *volt.Request) error {
		voltid, ok := volt.ParseInt32(r.PathValue("id"))
		if !ok {
			return volt.ErrNotFound
		}
		return c.Posts.Update(w, r, voltid)
	}, errHandlerErrors)))

	// DELETE /posts/:id(int32) → Posts.Delete [pipe: api]
	mux.Handle("DELETE /posts/{id}", pipe0(volt.Handler("DELETE /posts/{id}", func(w http.ResponseWriter, r *volt.Request) error {
		voltid, ok := volt.ParseInt32(r.PathValue("id"))
		if !ok {
			return volt.ErrNotFound
		}
		return c.Posts.Delete(w, r, voltid)
	}, errHandlerErrors)))

	// GET /api/comments → Comments.Index [pipe: api]
	mux.Handle("GET /api/comments", pipe0(volt.Handler("GET /api/comments", func(w http.ResponseWriter, r *volt.Request) error {
		return c.Comments.Index(w, r)
	}, errHandlerErrors)))

	// POST /api/comments → Comments.Create [pipe: api]
	mux.Handle("POST /api/comments", pipe0(volt.Handler("POST /api/comments", func(w http.ResponseWriter, r *volt.Request) error {
		return c.Comments.Create(w, r)
	}, errHandlerErrors)))

	// GET /api/comments/:id(int32) → Comments.Show [pipe: api]
	mux.Handle("GET /api/comments/{id}", pipe0(volt.Handler("GET /api/comments/{id}", func(w http.ResponseWriter, r *volt.Request) error {
		voltid, ok := volt.ParseInt32(r.PathValue("id"))
		if !ok {
			return volt.ErrNotFound
		}
		return c.Comments.Show(w, r, voltid)
	}, errHandlerErrors)))

	// PATCH /api/comments/:id(int32) → Comments.Update [pipe: api]
	mux.Handle("PATCH /api/comments/{id}", pipe0(volt.Handler("PATCH /api/comments/{id}", func(w http.ResponseWriter, r *volt.Request) error {
		voltid, ok := volt.ParseInt32(r.PathValue("id"))
		if !ok {
			return volt.ErrNotFound
		}
		return c.Comments.Update(w, r, voltid)
	}, errHandlerErrors)))

	// PUT /api/comments/:id(int32) → Comments.Update [pipe: api]
	mux.Handle("PUT /api/comments/{id}", pipe0(volt.Handler("PUT /api/comments/{id}", func(w http.ResponseWriter, r *volt.Request) error {
		voltid, ok := volt.ParseInt32(r.PathValue("id"))
		if !ok {
			return volt.ErrNotFound
		}
		return c.Comments.Update(w, r, voltid)
	}, errHandlerErrors)))
}

// errHandlerErrors adapts the error_handler declared in the routes.
var errHandlerErrors = volt.ErrorHandler(Errors)
