// Code generated by volt gen. DO NOT EDIT.
//
// Source: package app

package app

import (
	"github.com/Piechutowski/volt"
)

// Table lists every route of the package, in declaration order:
// the routing DSL as introspectable data ('volt routes', metrics
// labels, and downstream derivations read this).
var Table = []volt.Route{
	{Method: "GET", Pattern: "/health", Spelled: "/health", Controller: "Health", Action: "Check", Helper: "PathCheck"},
	{Method: "GET", Pattern: "/posts", Spelled: "/posts", Controller: "Posts", Action: "Index", Helper: "PathPosts"},
	{Method: "GET", Pattern: "/posts/new", Spelled: "/posts/new", Controller: "Posts", Action: "New", Helper: "PathNewPost"},
	{Method: "POST", Pattern: "/posts", Spelled: "/posts", Controller: "Posts", Action: "Create"},
	{Method: "GET", Pattern: "/posts/{id}", Spelled: "/posts/:id(int32)", Controller: "Posts", Action: "Show", Helper: "PathPost", Params: []volt.RouteParam{{Name: "id", Type: "int32"}}},
	{Method: "GET", Pattern: "/posts/{id}/edit", Spelled: "/posts/:id(int32)/edit", Controller: "Posts", Action: "Edit", Helper: "PathEditPost", Params: []volt.RouteParam{{Name: "id", Type: "int32"}}},
	{Method: "PATCH", Pattern: "/posts/{id}", Spelled: "/posts/:id(int32)", Controller: "Posts", Action: "Update", Params: []volt.RouteParam{{Name: "id", Type: "int32"}}},
	{Method: "PUT", Pattern: "/posts/{id}", Spelled: "/posts/:id(int32)", Controller: "Posts", Action: "Update", Params: []volt.RouteParam{{Name: "id", Type: "int32"}}},
	{Method: "DELETE", Pattern: "/posts/{id}", Spelled: "/posts/:id(int32)", Controller: "Posts", Action: "Delete", Params: []volt.RouteParam{{Name: "id", Type: "int32"}}},
	{Method: "GET", Pattern: "/api/comments", Spelled: "/api/comments", Controller: "Comments", Action: "Index", Helper: "PathAPIComments"},
	{Method: "POST", Pattern: "/api/comments", Spelled: "/api/comments", Controller: "Comments", Action: "Create"},
	{Method: "GET", Pattern: "/api/comments/{id}", Spelled: "/api/comments/:id(int32)", Controller: "Comments", Action: "Show", Helper: "PathAPIComment", Params: []volt.RouteParam{{Name: "id", Type: "int32"}}},
	{Method: "PATCH", Pattern: "/api/comments/{id}", Spelled: "/api/comments/:id(int32)", Controller: "Comments", Action: "Update", Params: []volt.RouteParam{{Name: "id", Type: "int32"}}},
	{Method: "PUT", Pattern: "/api/comments/{id}", Spelled: "/api/comments/:id(int32)", Controller: "Comments", Action: "Update", Params: []volt.RouteParam{{Name: "id", Type: "int32"}}},
}
