// Code generated by volt gen. DO NOT EDIT.
//
// Source: package app

package app

import (
	"github.com/Piechutowski/volt"
)

// PathCheck returns the path for GET /health (Health.Check).
func PathCheck(opts ...volt.URLOption) string {
	return volt.URL("/health", opts...)
}

// PathPosts returns the path for GET /posts (Posts.Index).
func PathPosts(opts ...volt.URLOption) string {
	return volt.URL("/posts", opts...)
}

// PathNewPost returns the path for GET /posts/new (Posts.New).
func PathNewPost(opts ...volt.URLOption) string {
	return volt.URL("/posts/new", opts...)
}

// PathPost returns the path for GET /posts/:id(int32) (Posts.Show).
func PathPost(id int32, opts ...volt.URLOption) string {
	return volt.URL("/posts/"+volt.SegInt(int64(id)), opts...)
}

// PathEditPost returns the path for GET /posts/:id(int32)/edit (Posts.Edit).
func PathEditPost(id int32, opts ...volt.URLOption) string {
	return volt.URL("/posts/"+volt.SegInt(int64(id))+"/edit", opts...)
}

// PathAPIComments returns the path for GET /api/comments (Comments.Index).
func PathAPIComments(opts ...volt.URLOption) string {
	return volt.URL("/api/comments", opts...)
}

// PathAPIComment returns the path for GET /api/comments/:id(int32) (Comments.Show).
func PathAPIComment(id int32, opts ...volt.URLOption) string {
	return volt.URL("/api/comments/"+volt.SegInt(int64(id)), opts...)
}
