package lang

import (
	"os"
	"path/filepath"
	"testing"
)

// TestGoFuncsScanSkipsGenerated proves the scan for Go references
// ignores volt's own output: a generated file is recognized by its
// first line alone and never parsed, so a check or a plug cannot
// resolve to it and a million generated lines cost the check nothing
// (D81).
func TestGoFuncsScanSkipsGenerated(t *testing.T) {
	dir := t.TempDir()
	files := map[string]string{
		"checks.go":     "package p\n\nfunc Positive(v int32) error { return nil }\n",
		"nao_models.go": "// Code generated by nao gen from package p; DO NOT EDIT.\n\npackage p\n\nfunc Generated() {}\n",
		"note.go":       "// Code generated is what this comment is about, not a marker\n\npackage p\n\nfunc Commented() {}\n",
	}
	for name, src := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(src), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	for _, src := range GoSourcesRead(dir) {
		if want := src.Name == "nao_models.go"; src.Head != want {
			t.Errorf("%s read as a head: %v, want %v", src.Name, src.Head, want)
		}
	}
	funcs, broken := GoFuncsScan(dir)
	if len(broken) != 0 {
		t.Fatalf("broken: %v", broken)
	}
	for name, want := range map[string]bool{"Positive": true, "Commented": true, "Generated": false} {
		if _, ok := funcs[name]; ok != want {
			t.Errorf("%s found=%v, want %v", name, ok, want)
		}
	}
}
