// Code generated by volt gen. DO NOT EDIT.
//
// Source: package app

package app

import (
	"github.com/Piechutowski/volt"
)

// PathRoot returns the path for GET / (Home.Index).
func PathRoot(opts ...volt.URLOption) string {
	return volt.URL("/", opts...)
}

// PathTeapot returns the path for GET /teapot (Home.Teapot).
func PathTeapot(opts ...volt.URLOption) string {
	return volt.URL("/teapot", opts...)
}

// PathPing returns the path for any /ping (Home.Ping).
func PathPing(opts ...volt.URLOption) string {
	return volt.URL("/ping", opts...)
}

// PathAdminStats returns the path for GET /admin/stats (Admin.Stats).
func PathAdminStats(opts ...volt.URLOption) string {
	return volt.URL("/admin/stats", opts...)
}

// PathOpsFail returns the path for GET /ops/fail (Ops.Fail).
func PathOpsFail(opts ...volt.URLOption) string {
	return volt.URL("/ops/fail", opts...)
}

// PathUsers returns the path for GET /users (Users.Index).
func PathUsers(opts ...volt.URLOption) string {
	return volt.URL("/users", opts...)
}

// PathNewUser returns the path for GET /users/new (Users.New).
func PathNewUser(opts ...volt.URLOption) string {
	return volt.URL("/users/new", opts...)
}

// PathUser returns the path for GET /users/:id(int32) (Users.Show).
func PathUser(id int32, opts ...volt.URLOption) string {
	return volt.URL("/users/"+volt.SegInt(int64(id)), opts...)
}

// PathEditUser returns the path for GET /users/:id(int32)/edit (Users.Edit).
func PathEditUser(id int32, opts ...volt.URLOption) string {
	return volt.URL("/users/"+volt.SegInt(int64(id))+"/edit", opts...)
}

// PathAvatar returns the path for GET /users/:id(int32)/avatar (Users.Avatar).
func PathAvatar(id int32, opts ...volt.URLOption) string {
	return volt.URL("/users/"+volt.SegInt(int64(id))+"/avatar", opts...)
}

// PathServe returns the path for GET /files/:path... (Files.Serve).
func PathServe(path string, opts ...volt.URLOption) string {
	return volt.URL("/files/"+volt.SegWild(path), opts...)
}

// PathTag returns the path for GET /tags/:name (Tags.Show).
func PathTag(name string, opts ...volt.URLOption) string {
	return volt.URL("/tags/"+volt.Seg(name), opts...)
}

// PathPage returns the path for GET /pages/:num(int) (Pages.Show).
func PathPage(num int, opts ...volt.URLOption) string {
	return volt.URL("/pages/"+volt.SegInt(int64(num)), opts...)
}

// PathEpoch returns the path for GET /epochs/:stamp(int64) (Epochs.Show).
func PathEpoch(stamp int64, opts ...volt.URLOption) string {
	return volt.URL("/epochs/"+volt.SegInt(stamp), opts...)
}
