// Package rt is the runtime support package for code generated by dbml
// gen. It is the only non-stdlib import generated code is allowed
// (decision D03): a nullable value type, the database handle interface,
// a transaction helper, an opener that applies the SQLite pragmas the
// generated SQL assumes, a prepared-statement cache, and the dynamic
// query layer (query.go) — typed column handles, predicates and options
// as inert data, and their deterministic SQL interpreter (D28-D34).
//
// The package registers no driver. The application chooses one (any
// database/sql SQLite driver) and passes its name to Open, so rt itself
// stays dependency-free and cgo-free.
package rt

import (
	"context"
	"database/sql"
	"fmt"
)

// DBTX is what generated queries need from a database handle. Both
// *sql.DB and *sql.Tx satisfy it, which is how the same generated method
// runs inside and outside a transaction.
type DBTX interface {
	ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error)
	PrepareContext(ctx context.Context, query string) (*sql.Stmt, error)
	QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)
	QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row
}

// ErrNotFound is returned by generated Get/Update/Delete methods when no
// row matches the given identity. It is sql.ErrNoRows, so existing
// errors.Is(err, sql.ErrNoRows) checks keep working.
var ErrNotFound = sql.ErrNoRows

// beginner is the subset of *sql.DB that can start a transaction.
type beginner interface {
	BeginTx(ctx context.Context, opts *sql.TxOptions) (*sql.Tx, error)
}

// Tx runs fn inside a transaction: begin, fn, commit — with a rollback on
// error or panic. db is typically a *sql.DB; passing a handle that cannot
// begin a transaction (such as a *sql.Tx: SQLite has no nested
// transactions) is an error.
func Tx(ctx context.Context, db DBTX, fn func(tx *sql.Tx) error) (err error) {
	b, ok := db.(beginner)
	if !ok {
		return fmt.Errorf("rt.Tx: %T cannot begin a transaction", db)
	}
	tx, err := b.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	done := false
	defer func() {
		if !done {
			_ = tx.Rollback() // no-op after Commit; the commit error already reports
		}
	}()
	if err := fn(tx); err != nil {
		return err
	}
	done = true
	return tx.Commit()
}

// Open opens a SQLite database via the named database/sql driver and
// applies the pragmas the generated code is designed for:
//
//	journal_mode = WAL    readers do not block the writer
//	busy_timeout = 5000   wait instead of failing with SQLITE_BUSY
//	foreign_keys = ON     the generated DDL declares real foreign keys
//
// Pragmas are per-connection in SQLite, so Open pins the pool to a single
// connection. SQLite has a single writer anyway; one connection makes the
// pragmas hold for every statement and removes in-process busy contention.
// (Read scaling across many connections can be revisited later.)
func Open(driver, dsn string) (*sql.DB, error) {
	db, err := sql.Open(driver, dsn)
	if err != nil {
		return nil, err
	}
	db.SetMaxOpenConns(1)
	for _, pragma := range []string{
		"PRAGMA journal_mode = WAL",
		"PRAGMA busy_timeout = 5000",
		"PRAGMA foreign_keys = ON",
	} {
		if _, err := db.Exec(pragma); err != nil {
			_ = db.Close()
			return nil, fmt.Errorf("rt.Open: %s: %w", pragma, err)
		}
	}
	return db, nil
}
